### ISSUE TITLE
babbar !?

### ISSUE THREAD

**Issue by daikoz** [crowdsecurity/hub#1039]
Why babbar.eu is in whitelists/benign_bots/search_engine_crawlers/rdns_seo_bots.txt ?
it is not a search engine.

**Comment by LaurenceJJones** [comment]
> Why babbar.eu is in whitelists/benign_bots/search_engine_crawlers/rdns_seo_bots.txt ?
> it is not a search engine.
> 
> 

Sometimes, we bundle other legit crawlers into the same RDNS file

https://www.babbar.tech/crawler
