### ISSUE TITLE
Extend Odoo collection

### ISSUE THREAD

**Issue by sreisich** [crowdsecurity/hub#1053]
Hello,

It would be very nice if the Odoo collection could be extended. Odoo has a database manager that requires a master password to work.
The database manager can be accessed by adding /web/database/manager to the url. When an action is posted, the master password is used for authentication. If the password is incorrect, we get the following log, in this example the action was "drop":

```
2024-06-11 20:32:22,753 399 INFO None werkzeug: xx.xx.xx.xx - - [11/Jun/2024 20:32:22] "POST /web/database/drop HTTP/1.1" 200 - 4 0.003 1.419
2024-06-11 20:32:24,858 398 ERROR None odoo.addons.web.controllers.database: Database deletion error.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/web/controllers/database.py", line 113, in drop
    dispatch_rpc('db', 'drop', [master_pwd, name])
  File "/home/odoo/src/odoo/odoo/http.py", line 369, in dispatch_rpc
    return dispatch(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/odoo/service/db.py", line 479, in dispatch
    check_super(passwd)
  File "/home/odoo/src/odoo/odoo/service/db.py", line 53, in check_super
   raise odoo.exceptions.AccessDenied()
odoo.exceptions.AccessDenied: Access Denied
2024-06-11 20:32:24,930 398 INFO None werkzeug: xx.xx.xx.xx - - [11/Jun/2024 20:32:24] "POST /web/database/drop HTTP/1.1" 200 - 4 0.003 0.107
2024-06-11 20:36:05,263 398 INFO test-db werkzeug: xx.xx.xx.xx - - [11/Jun/2024 20:36:05] "GET / HTTP/1.1" 303 - 2 0.002 0.013
```

So CrowdSec should check for the url `/web/database` and the line `odoo.exceptions.AccessDenied: Access Denied`

**Comment by LaurenceJJones** [comment]
> Hello,
> 
> It would be very nice if the Odoo collection could be extended. Odoo has a database manager that requires a master password to work. The database manager can be accessed by adding /web/database/manager to the url. When an action is posted, the master password is used for authentication. If the password is incorrect, we get the following log, in this example the action was "drop":
> 
> ```
> 2024-06-11 20:32:22,753 399 INFO None werkzeug: xx.xx.xx.xx - - [11/Jun/2024 20:32:22] "POST /web/database/drop HTTP/1.1" 200 - 4 0.003 1.419
> 2024-06-11 20:32:24,858 398 ERROR None odoo.addons.web.controllers.database: Database deletion error.
> Traceback (most recent call last):
>   File "/home/odoo/src/odoo/addons/web/controllers/database.py", line 113, in drop
>     dispatch_rpc('db', 'drop', [master_pwd, name])
>   File "/home/odoo/src/odoo/odoo/http.py", line 369, in dispatch_rpc
>     return dispatch(method, params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/odoo/src/odoo/odoo/service/db.py", line 479, in dispatch
>     check_super(passwd)
>   File "/home/odoo/src/odoo/odoo/service/db.py", line 53, in check_super
>    raise odoo.exceptions.AccessDenied()
> odoo.exceptions.AccessDenied: Access Denied
> 2024-06-11 20:32:24,930 398 INFO None werkzeug: xx.xx.xx.xx - - [11/Jun/2024 20:32:24] "POST /web/database/drop HTTP/1.1" 200 - 4 0.003 0.107
> 2024-06-11 20:36:05,263 398 INFO test-db werkzeug: xx.xx.xx.xx - - [11/Jun/2024 20:36:05] "GET / HTTP/1.1" 303 - 2 0.002 0.013
> ```
> 
> So CrowdSec should check for the url `/web/database` and the line `odoo.exceptions.AccessDenied: Access Denied`

It _could_ be done but would be a massive PITA because its basically a traceback call, if odoo responded with a reasonable response code instead of 200 like 403 then be easy to match the URL.

**Comment by sreisich** [comment]
I don't know what you mean with PITA, but that is how Odoo is handling a auth error in his database manager at  /web/database...

**Comment by LaurenceJJones** [comment]
> I don't know what you mean with PITA, but that is how Odoo is handling a auth error in his database manager at /web/database...

just slang for `pain in the ass` as CrowdSec can handle multi log lines but its not pretty. So for now the answer is no as the issue you have you have to "guess" that the last log line is the one that causes the exception which may not be the case.

**Comment by sreisich** [comment]
I got your point. What you think about just check the line
`2024-06-11 20:32:24,858 398 ERROR None odoo.addons.web.controllers.database: Database deletion error.`
for `ERROR ` and `odoo.addons.web.controllers.database`

It should be fine to block every user that raises to much errors in the module `odoo.addons.web.controllers.database`...

**Comment by LaurenceJJones** [comment]
> I got your point. What you think about just check the line `2024-06-11 20:32:24,858 398 ERROR None odoo.addons.web.controllers.database: Database deletion error.` for `ERROR ` and `odoo.addons.web.controllers.database`
> 
> It should be fine to block every user that raises to much errors in the module `odoo.addons.web.controllers.database`...

The issue is do we just guess that the last IP is the one that caused the exception? as the line doesnt have the IP within it.

**Comment by sreisich** [comment]
aahh, ok, now I really got your point :-) You are right, this is indeed not a reliable way...
It's a pitty...
