### ISSUE TITLE
failed to compile node 'crowdsecurity/geoip-enrich'

### ISSUE THREAD

**Issue by c-premus** [crowdsecurity/hub#1062]
**Describe the bug**
Crowdsec fails to start with:

```
failed to compile node 'crowdsecurity/geoip-enrich' in '/etc/crowdsec/parsers/s02-enrich/geoip-enrich.yaml' : compilation of 'let ipv6Check = IsIPV6(evt.Meta.source_ip);
\"source_ip\" in evt.Meta &&
(
  not ipv6Check &&
  not (IpInRange(evt.Meta.source_ip, \"127.0.0.0/8\") || IpInRange(evt.Meta.source_ip, \"192.168.0.0/16\") || IpInRange(evt.Meta.source_ip, \"172.16.0.0/12\") || IpInRange(evt.Meta.source_ip, \"10.0.0.0/8\"))
) ||
(
  ipv6Check &&
  not (IpInRange(evt.Meta.source_ip, \"::1/128\") || IpInRange(evt.Meta.source_ip, \"fd00::/8\") || IpInRange(evt.Meta.source_ip, \"fc00::/7\"))
)
' failed: unrecognized character: U+003B ';' (1:44)
 | let ipv6Check = IsIPV6(evt.Meta.source_ip);
 | ...........................................
```

**To Reproduce**
```
cscli parsers install crowdsecurity/geoip-enrich
systemctl reload crowdsec
```

**Expected behavior**
I didn't expect it to not complie

**Additional context**

version: v1.6.2-debian-pragmatic-amd64-16bfab86
Codename: alphaga
BuildDate: 2024-05-31_09:18:01
GoVersion: 1.22.2
Platform: linux
libre2: C++
User-Agent: crowdsec/v1.6.2-debian-pragmatic-amd64-16bfab86-linux
Constraint_parser: >= 1.0, <= 3.0
Constraint_scenario: >= 1.0, <= 3.0
Constraint_api: v1
Constraint_acquis: >= 1.0, < 2.0

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

**Comment by c-premus** [comment]
That was it.

```
which -a crowdsec

/usr/local/bin/crowdsec
/usr/bin/crowdsec
/bin/crowdsec
```

/usr/local/bin/crowdsec was the culprit.  I tried reinstalling from apt but it was still outdated.  I ended up manually copying crowdsec from /bin to /usr/local/bin as the systemd unit file uses /usr/local/bin/crowdsec

```
[Unit]
Description=Crowdsec agent
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=notify
Environment=LC_ALL=C LANG=C
ExecStartPre=/usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml -t -error
ExecStart=/usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml
#ExecStartPost=/bin/sleep 0.1
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target
```

**Comment by LaurenceJJones** [comment]
> That was it.
> 
> ```
> which -a crowdsec
> 
> /usr/local/bin/crowdsec
> /usr/bin/crowdsec
> /bin/crowdsec
> ```
> 
> /usr/local/bin/crowdsec was the culprit. I tried reinstalling from apt but it was still outdated. I ended up manually copying crowdsec from /bin to /usr/local/bin as the systemd unit file uses /usr/local/bin/crowdsec
> 
> ```
> [Unit]
> Description=Crowdsec agent
> After=syslog.target network.target remote-fs.target nss-lookup.target
> 
> [Service]
> Type=notify
> Environment=LC_ALL=C LANG=C
> ExecStartPre=/usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml -t -error
> ExecStart=/usr/local/bin/crowdsec -c /etc/crowdsec/config.yaml
> #ExecStartPost=/bin/sleep 0.1
> ExecReload=/bin/kill -HUP $MAINPID
> Restart=always
> RestartSec=60
> 
> [Install]
> WantedBy=multi-user.target
> ```

Hmm did you install the software from two places? EG: one via our repository and then one via manually downloading from our github?
