### ISSUE TITLE
sshd parser false positive regarding AllowUsers 

### ISSUE THREAD

**Issue by onxzy** [crowdsecurity/hub#1064]
There seems to be an issue with the sshd-logs parser since commit [b7504a0](https://github.com/crowdsecurity/hub/commit/b7504a04c787766655096d350a9135dbe26e20d3) 

When using ansible my ip gets flagged as `ssh-bf` and `ssh-slow-bf` due to a `ssh_failed-auth` event from the sshd parser.
After digging I found the log line responsible for this flag :
```
Jun 29 16:53:37 my-vps sshd[3685002]: Close session: user ansible from 123.4.5.6 port 34928 id 0
```
which match the `SSHD_NOT_ALLOWED_USER` pattern in the sshd-logs parser.

**Additional context :**
```
# crowdsec -version
version: v1.6.2-16bfab86
Codename: alphaga
BuildDate: 2024-06-05_14:18:52
GoVersion: 1.22.3
Platform: docker
libre2: C++
User-Agent: crowdsec/v1.6.2-16bfab86-docker
Constraint_parser: >= 1.0, <= 3.0
Constraint_scenario: >= 1.0, <= 3.0
Constraint_api: v1
Constraint_acquis: >= 1.0, < 2.0
```

I installed the parser using the `cscli hub update` command.

**Comment by LaurenceJJones** [comment]
> There seems to be an issue with the sshd-logs parser since commit [b7504a0](https://github.com/crowdsecurity/hub/commit/b7504a04c787766655096d350a9135dbe26e20d3) 
> 
> When using ansible my ip gets flagged as `ssh-bf` and `ssh-slow-bf` due to a `ssh_failed-auth` event from the sshd parser.
> After digging I found the log line responsible for this flag :
> ```
> Jun 29 16:53:37 my-vps sshd[3685002]: Close session: user ansible from 123.4.5.6 port 34928 id 0
> ```
> which match the `SSHD_NOT_ALLOWED_USER` pattern in the sshd-logs parser.
> 
> **Additional context :**
> ```
> # crowdsec -version
> version: v1.6.2-16bfab86
> Codename: alphaga
> BuildDate: 2024-06-05_14:18:52
> GoVersion: 1.22.3
> Platform: docker
> libre2: C++
> User-Agent: crowdsec/v1.6.2-16bfab86-docker
> Constraint_parser: >= 1.0, <= 3.0
> Constraint_scenario: >= 1.0, <= 3.0
> Constraint_api: v1
> Constraint_acquis: >= 1.0, < 2.0
> ```
> 
> I installed the parser using the `cscli hub update` command.

Apologises, I replied to your discord if it's the same user. I will refactor the PR and push some valid auth test cases that should prevent an FP in the future.
