### ISSUE TITLE
No range found for ip

### ISSUE THREAD

**Issue by Simbiat** [crowdsecurity/hub#1077]
**Describe the bug**
My logs are flooded by messages like
```
time="2024-07-14T00:00:21Z" level=warning msg="No range found for ip '172.21.0.1'" id=wispy-morning method=IpToRange name=crowdsecurity/geoip-enrich stage=s02-enrich
```
It is always `172.21.0.1`, which is internal docker host IP (I am using `subnet: 172.21.0.0/16` in docker-compose). Not entirely sure where host is being taken from, but that does not matter much, I think. `geoip-enrich.yaml` is supposed to exclude this IP with its `IpInRange(evt.Meta.source_ip, "172.16.0.0/12")` but apparently it does not.
Furthermore `geoip-enrich.yaml` does not include all private ranges (at least according to [Wiki](https://en.wikipedia.org/wiki/Reserved_IP_addresses)), so I think we need a solution to suppress these warnings somehow.

**To Reproduce**
Not sure if there is much of reproduction steps here, but my docker-compose.yml and respective config files are [here](https://github.com/Simbiat/simbiat.ru)

**Expected behavior**
No spam of warnings about an IP not being present in GeoIP databases

**Comment by Simbiat** [comment]
moments after I wrote this I decided to check contents of docker image and... `geoip-enrich.yaml` there does not actually have this limitation, although it is apparently a month old. was it not published to hub yet?

**Comment by LaurenceJJones** [comment]
> moments after I wrote this I decided to check contents of docker image and... `geoip-enrich.yaml` there does not actually have this limitation, although it is apparently a month old. was it not published to hub yet?

Hmmm no it should be on the hub, you need to be on latest `1.6.2` for CrowdSec to download the contents though if your on any previous version it will download the older copies.

**Comment by Simbiat** [comment]
I am using `crowdsecurity/crowdsec:latest`, so... Not sure why it's not up-to-date then. Anything I can do to debug this?

**Comment by LaurenceJJones** [comment]
> I am using `crowdsecurity/crowdsec:latest`, so... Not sure why it's not up-to-date then. Anything I can do to debug this?

Well latest will pull the latest image, when you bring up the stack. So if you run `docker ps` what the current image version running?

**Comment by Simbiat** [comment]
```
version: v1.6.2-16bfab86
Codename: alphaga
BuildDate: 2024-06-05_14:25:55
GoVersion: 1.22.3
Platform: docker
libre2: C++
User-Agent: crowdsec/v1.6.2-16bfab86-docker
Constraint_parser: >= 1.0, <= 3.0
Constraint_scenario: >= 1.0, <= 3.0
Constraint_api: v1
Constraint_acquis: >= 1.0, < 2.0
```
Built in May, but `geoip-enrich.yaml` was updated in June, although, I would guess that should not matter?

**Comment by LaurenceJJones** [comment]
And what are the contents for your local geoip enricher? because the issue with docker is there is no cronjob to update the files automatically. So you need to either restart the image OR have an external cronjob to exec into the container and run

```
cscli hub update
cscli hub upgrade
```

**Comment by Simbiat** [comment]
That's the thing: even when I create a new image from scratch, it still has the outdated `geoip-enrich.yaml` contents

**Comment by LaurenceJJones** [comment]
> That's the thing: even when I create a new image from scratch, it still has the outdated `geoip-enrich.yaml` contents

Yes, as the currently built image _would_ have the file locally so it doesnt refetch them. Hmm let me do some testing.

**Comment by Simbiat** [comment]
also, I would not mind running a CRON job, but... I was not able to. For some reason, if I add `command` that would register a CRON job before triggering endpoint, it just ignores the `command`, and if create a custom Dockerfile, where I do the same thing, CrowdSec does not add its own CRON jobs. It's the only container so far I have such issues with, because my PHP and database [containers](https://github.com/Simbiat/simbiat.ru/blob/master/docker-compose.yml) do execute `command` normally. Was not able to determine why that happens.

**Comment by LaurenceJJones** [comment]
> also, I would not mind running a CRON job, but... I was not able to. For some reason, if I add `command` that would register a CRON job before triggering endpoint, it just ignores the `command`, and if create a custom Dockerfile, where I do the same thing, CrowdSec does not add its own CRON jobs. It's the only container so far I have such issues with, because my PHP and database [containers](https://github.com/Simbiat/simbiat.ru/blob/master/docker-compose.yml) do execute `command` normally. Was not able to determine why that happens.

We are based on alpine and don't install the cronjob dependencies on our image (unless you do via a `command`), as per docker philosophy the image should only do one job and that is to run the CrowdSec binary and not have any other commands run inside.

**Comment by Simbiat** [comment]
Then what are these?
![image](https://github.com/user-attachments/assets/9c29d27a-f30f-44ac-bf1a-cf52510568c7)
it still does not explain why "command" is ignored for this container specifically, too. But that's a separate thing.

**Comment by LaurenceJJones** [comment]
> Then what are these? ![image](https://private-user-images.githubusercontent.com/6022665/348674745-9c29d27a-f30f-44ac-bf1a-cf52510568c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDI3MTIsIm5iZiI6MTcyMTA0MjQxMiwicGF0aCI6Ii82MDIyNjY1LzM0ODY3NDc0NS05YzI5ZDI3YS1mMzBmLTQ0YWMtYmYxYS1jZjUyNTEwNTY4YzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMTEyMDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2IxYWU2MzgzNzI5NmNmMjlmM2FhNmJjYjA0YWIxYzMzNmMwYzg3Y2I4MjMyODMyYjAxMTIxMTRkOGM2MWU1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4Y2GwXUvmS-lRvvKnF-CUrtbhXqNeD1vqC0-Q4lGtpI) it still does not explain why "command" is ignored for this container specifically, too. But that's a separate thing.

Yeah seems by default alpine installs the busybox package which has crond but because its not actively running via `ps` so it not running as a service

```
/ # ps -a
PID   USER     TIME  COMMAND
1 root      0:02 crowdsec -c /etc/crowdsec/config.yaml
453 root      0:00 ash
461 root      0:00 ps -a
/ # apk list
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.20/main: No such file or directory
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.20/community: No such file or directory
alpine-baselayout-3.6.5-r0 x86_64 {alpine-baselayout} (GPL-2.0-only) [installed]
alpine-baselayout-data-3.6.5-r0 x86_64 {alpine-baselayout} (GPL-2.0-only) [installed]
alpine-keys-2.4-r1 x86_64 {alpine-keys} (MIT) [installed]
apk-tools-2.14.4-r0 x86_64 {apk-tools} (GPL-2.0-only) [installed]
bash-5.2.26-r0 x86_64 {bash} (GPL-3.0-or-later) [installed]
busybox-1.36.1-r28 x86_64 {busybox} (GPL-2.0-only) [installed]
busybox-binsh-1.36.1-r28 x86_64 {busybox} (GPL-2.0-only) [installed]
ca-certificates-bundle-20240226-r0 x86_64 {ca-certificates} (MPL-2.0 AND MIT) [installed]
libacl-2.3.2-r0 x86_64 {acl} (LGPL-2.1-or-later AND GPL-2.0-or-later) [installed]
libcrypto3-3.3.0-r2 x86_64 {openssl} (Apache-2.0) [installed]
libncursesw-6.4_p20240420-r0 x86_64 {ncurses} (X11) [installed]
libssl3-3.3.0-r2 x86_64 {openssl} (Apache-2.0) [installed]
libxxhash-0.8.2-r2 x86_64 {xxhash} (BSD-2-Clause) [installed]
lz4-libs-1.9.4-r5 x86_64 {lz4} (BSD-2-Clause AND GPL-2.0-only) [installed]
musl-1.2.5-r0 x86_64 {musl} (MIT) [installed]
musl-utils-1.2.5-r0 x86_64 {musl} (MIT AND BSD-2-Clause AND GPL-2.0-or-later) [installed]
ncurses-terminfo-base-6.4_p20240420-r0 x86_64 {ncurses} (X11) [installed]
popt-1.19-r3 x86_64 {popt} (MIT) [installed]
readline-8.2.10-r0 x86_64 {readline} (GPL-3.0-or-later) [installed]
rsync-3.3.0-r0 x86_64 {rsync} (GPL-3.0-or-later) [installed]
scanelf-1.3.7-r2 x86_64 {pax-utils} (GPL-2.0-only) [installed]
ssl_client-1.36.1-r28 x86_64 {busybox} (GPL-2.0-only) [installed]
tzdata-2024a-r1 x86_64 {tzdata} (Public-Domain) [installed]
zlib-1.3.1-r1 x86_64 {zlib} (Zlib) [installed]
zstd-libs-1.5.6-r0 x86_64 {zstd} (BSD-3-Clause OR GPL-2.0-or-later) [installed]
```

**Comment by Simbiat** [comment]
`cscli hub update` is ran only if `"/etc/crowdsec/hub/.index.json"` is mounted, but I did not mound `/etc/crowdsec/` because it's not mounted in [Caddy example](https://github.com/crowdsecurity/example-docker-compose/blob/main/caddy/docker-compose.yml) for compose. Similar thing for `cscli hub upgrade`, but I do have data folder mounted.
I am not sure update/upgrade should be limited like this. I do not want to mount any of the configs besides the ones, that I do customize. I am also not sure if there is much benefit in mounting data folder, too, but maybe that does help. But anyway, it just does not make sense to not run update/upgrade even if respective folders are not mounted. If user is doing this with some valid reason (whatever it may be), it is possible that they will end up with outdated setup, and thus - vulnerable.

**Comment by LaurenceJJones** [comment]
Closing issue due to changes in CrowdSec where this message will be nullified as the warning is not the same as the issue. If you still have issue with hub updates from a mmb standpoint please open an issue on main CrowdSec repository.
