### ISSUE TITLE
Can't parse mail address in paperless-ngx

### ISSUE THREAD

**Issue by Nihimia** [crowdsecurity/hub#1127]
Hello !

**Describe the bug**
Paperless-ngx parser won't work  if mail address is used as username. Parser work if used with a "normal" username.

**To Reproduce**
Just try to log on paperless-ngx (I'm using v2.12.1) with a mail address, with, if applicable, wrong password.

**Expected behavior**
Parser work.

**Screenshots**
![image](https://github.com/user-attachments/assets/808533c7-1167-481c-90fe-d5fa6bd08ee4)

![image](https://github.com/user-attachments/assets/4a326d8a-2610-46c3-9f8e-51d5b15e24ea)

**Additional context**

If needed, where's my acquisition file : 

```bash
filenames:
  - /logs/paperless/paperless.log
labels:
  type: Paperless-ngx
```

In the paperless-ngx parser, I tried to replace %{USERNAME:username} with %{DATA:username}, it works, but I'am clearly not sure if this is the best to do.

With this modification : 

![image](https://github.com/user-attachments/assets/6e2ae9cb-6f8f-49bd-b25b-5d4ede736a78)

Thank you !

**Comment by LaurenceJJones** [comment]
Thank you for a detailed issue and a proposed solution :+1: , tagging as good first and if nobody picks it up will update in due course from the team
