### ISSUE TITLE
False Positive: mjs static files are counted as dynamic assets

### ISSUE THREAD

**Issue by GNU-Plus-Windows-User** [crowdsecurity/hub#1165]
mjs isn't counted as an static file and is causing false positives with applications that make heavy use of mjs files (Such as Nextcloud). I don't know where static resources are defined so I'm opening an issue here.

**Comment by LaurenceJJones** [comment]
static is defined within the enricher itself via this line:

https://github.com/crowdsecurity/hub/blob/10fb69b2f29c6b96af8b95aaa89ca89fecebae57/parsers/s02-enrich/crowdsecurity/http-logs.yaml#L33

**Comment by GNU-Plus-Windows-User** [comment]
@LaurenceJJones aah that's where it is, I thought it was somewhere in the individual web server parsers

PR incoming
