### ISSUE TITLE
Commit cda30eb leads to a lot of false positives

### ISSUE THREAD

**Issue by christmart** [crowdsecurity/hub#1201]
Commit https://github.com/crowdsecurity/hub/commit/cda30eb1b2e5d61f2a0dfbebe2ffd379aca491ec leads to a lot false positives. It is common for web applications to probe for authentication requirements with requests like:

OPTIONS /SOGo/dav/username/

as returncode it gives a 401 which signals that authentication is required . The client then sends the same request with authentication, which succeeds with return code 200.

The old code checked explicitedly for method POST and did not trigger in this case. The new code in this commit does not check the method and results in a false positive. 

Maybe you should exclude OPTIONS methods.

**Comment by christmart** [comment]
method     │ PROPFIND                             │
│ method     │ OPTIONS                              │
│ method     │ REPORT                               │
│ status     │ 401                                  │
│ target_uri │ /SOGo/dav/username/                    │
│ target_uri │ /SOGo/dav/                           │

**Comment by LaurenceJJones** [comment]
> ```
> | method     │ PROPFIND                             │
> │ method     │ OPTIONS                              │
> │ method     │ REPORT                               │
> │ status     │ 401                                  │
> │ target_uri │ /SOGo/dav/username/                    │
> │ target_uri │ /SOGo/dav/                           │
> ```

However, from this it seems there are other types that leads to `401` such as `REPORT` and `PROPFIND` but I guess `OPTIONS` should be ignored.

I am thinking of reverting back to the original and filtering down to ones we are sure wont cause an issue

EG: `evt.Parsed.verb in ['GET', 'POST', 'HEAD']`

OR we could do the opposite and reverse ones we know can be prone to FP's

EG: `evt.Parsed.verb not in ['OPTIONS', 'PROPFIND', 'REPORT']`
