### ISSUE TITLE
Bouncer inclusion: cs-wordpress-bouncer

### ISSUE THREAD

**Issue by AlteredCoder** [crowdsecurity/hub#127]
Hello,

I would like to suggest the addition of the `cs-wordpress-bouncer` to the hub :

 - Source repository: https://github.com/crowdsecurity/cs-wordpress-bouncer
 - Licence : MIT
 - Current status : unstable
 - README/doc : https://github.com/crowdsecurity/cs-wordpress-bouncer/README.md
 - Existing tests :
    - functional tests : https://github.com/crowdsecurity/cs-wordpress-bouncer/blob/main/run-tests-with-all-wp-versions.sh

 - Short/Long description : OK
 - Howto : in README
 - At least one release : yes

**Comment by buixor** [comment]
merged
