### ISSUE TITLE
add qwant bot to goods actors collection

### ISSUE THREAD

**Issue by LtSich** [crowdsecurity/hub#153]
Apparently the reverse dns always finish with .search.qwant.com

host 91.242.162.40
40.162.242.91.in-addr.arpa domain name pointer qwantbot-91-242-162-40.search.qwant.com.

host 91.242.162.75
75.162.242.91.in-addr.arpa domain name pointer qwantbot-91-242-162-75.search.qwant.com.

host 91.242.162.65
65.162.242.91.in-addr.arpa domain name pointer qwantbot-91-242-162-65.search.qwant.com.

**Comment by buixor** [comment]
ah yes great, I'm baking a PR for this :)

**Comment by buixor** [comment]
merged https://github.com/crowdsecurity/hub/pull/154 :+1:
