### ISSUE TITLE
false positive with bad user agent

### ISSUE THREAD

**Issue by LtSich** [crowdsecurity/hub#159]
Today I've got this false positive on bad user agent, this is the user agent : 
Mozilla/5.0 (Linux; Android 4.4.2; Archos 59 Titanium Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.141 Mobile Safari/537.36

The link that I have is with "titan" in the bad user agent list that will match with Titanium here.

**Comment by buixor** [comment]
should be fixed with https://github.com/crowdsecurity/hub/pull/197
