### ISSUE TITLE
False positive with ssh-logs when disconnecting

### ISSUE THREAD

**Issue by dani** [crowdsecurity/hub#177]
the sshd-logs parser catches such logs as a failure 
```
Mar 08 22:34:28 pve2 sshd[36002]: Received disconnect from 10.11.12.13 port 17534:11: disconnected by user
Mar 08 22:34:28 pve2 sshd[36002]: Disconnected from user dani 10.11.12.13 port 17534
Mar 08 22:34:28 pve2 sshd[35968]: pam_unix(sshd:session): session closed for user dani
```
(the relevant line is the first one, the others are just for some context)
This is done by the SSHD_RECE_PREAUTH pattern, included in SSHD_PREAUTH, used in crowdsecurity/sshd-logs. Only problem is that these are from a legitimate session, when I disconnect. This triggers false positives, including each time a backup ends.

**Comment by dani** [comment]
This should be fixed with https://github.com/crowdsecurity/crowdsec/pull/668

**Comment by buixor** [comment]
merged, thanks
