### ISSUE TITLE
nginx parser : support basic auth error messages

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/hub#183]
As seen on gitter, nginx parser doesn't support basic auth, ie. `2021/03/16 08:29:32 [error] 5669#5669: *2829 user "123" was not found in "/etc/nginx/.htpasswd", ....`

It should be supported in a similar way to https://github.com/crowdsecurity/hub/blob/master/parsers/s01-parse/crowdsecurity/apache2-logs.yaml

**Comment by dezzzm** [comment]
Example of nginx error logs. lxc container ubuntu 20.04, nginx default settings:
2021/03/16 08:29:32 [error] 5669#5669: *2829 user "123" was not found in "/etc/nginx/.htpasswd", client: 22.22.22.22, server: dgu.site1.ru, request: "GET / HTTP/1.1", host: "dgu.site1.ru"
2021/03/16 09:11:59 [error] 5669#5669: *4030 user "123" was not found in "/etc/nginx/.htpasswd", client: 22.22.22.22, server: dgu.site1.ru, request: "GET / HTTP/1.1", host: "dgu.site1.ru"
2021/03/16 09:12:04 [error] 5669#5669: *4030 user "user1": password mismatch, client: 22.22.22.22, server: dgu.site1.ru, request: "GET / HTTP/1.1", host: "dgu.site1.ru"
2021/03/16 09:12:09 [error] 5669#5669: *4030 user "user1": password mismatch, client: 22.22.22.22, server: dgu.site1.ru, request: "GET / HTTP/1.1", host: "dgu.site1.ru"
