### ISSUE TITLE
crowdsecurity/http-xss-probbing: API error

### ISSUE THREAD

**Issue by saz** [crowdsecurity/hub#227]
I'm seeing the following error in the logs:
```
time="02-08-2021 14:59:14" level=info msg="(cd2049a0afe94d3fa00f31fc31696554Ua12Lr1XXecojaMs/crowdsec) crowdsecurity/http-xss-probbing by ip <redacted> (DE) : 4h ban on Ip <redacted>"
time="02-08-2021 14:59:14" level=error msg="while pushing to api : failed sending alert to LAPI: API error: unable to create alerts: creating alert events: ent: validator failed for field \"serialized\":
 value is greater than the required length: unable to insert bulk"
```

Any idea, why this is happening? It's also repeated every second until a reload.

**Comment by buixor** [comment]
Hello @saz !

At first glance, it seems that the data being pushed in serialized (which is captured data that stays locally to LAPI) is too big. There is currently a default of `4095` : we might want to either drop the limitation, strip data, or drop it if it excess size.

Do you have an easy way to reproduce ? else I'll look at it :+1:

**Comment by buixor** [comment]
https://github.com/crowdsecurity/crowdsec/pull/877 let's do both : bump size to 8k and progressively strip serialized size down hopping to make it fit :smile:

**Comment by saz** [comment]
Until now, I'm not able to reproduce the issue, it just shows up after some time. I've also enabled debug logging. But: since this time, it's not happening anymore :(

**Comment by buixor** [comment]
Hello,

It happened because the URI that was captured by crowdsec was roughly 4k and with the extra space eaten up by marshaling it would break the validation rule. Will be in next release :)

**Comment by blotus** [comment]
Hello,

[Crowdsec v1.2.0](https://github.com/crowdsecurity/crowdsec/releases/tag/v1.2.0) has been released, and it includes a fix for this error.

Let us know if you still have the issue after upgrading.
