### ISSUE TITLE
Document acquisition config for each parser properly

### ISSUE THREAD

**Issue by sbs2001** [crowdsecurity/hub#228]
Majority of our parsers don't document the acquisition config. Which makes it impossible to  use. For eg 

https://github.com/crowdsecurity/hub/blob/master/parsers/s01-parse/crowdsecurity/cpanel-logs.yaml
https://github.com/crowdsecurity/hub/blob/master/parsers/s01-parse/crowdsecurity/pgsql-logs.md

etc

**Comment by buixor** [comment]
done :)
