### ISSUE TITLE
crowdsecurity/seo-bots-whitelist: google bot comes from two different domain names

### ISSUE THREAD

**Issue by ThomasLohner** [crowdsecurity/hub#25]
Currently only `googlebot.com` is implemented but we are also seeing requests from `rate-limited-proxy-xxx.google.com`. This is confirmed by gooogle documentation: https://support.google.com/webmasters/answer/80553?hl=en

**Comment by AlteredCoder** [comment]
This has been fixed [here](https://github.com/crowdsecurity/hub/pull/26) thanks to this [here](https://github.com/crowdsecurity/sec-lists/blob/master/whitelists/benign_bots/search_engine_crawlers/rnds_seo_bots.regex)
