### ISSUE TITLE
Generic DoS/DDoS http scenarios ?

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/hub#260]
Following https://github.com/crowdsecurity/crowdsec/issues/978 it might make sense to have a generic DoS http detection for IPs that generate a huge amount of requests quickly.

**Comment by LaurenceJJones** [comment]
We do have scenarios written in https://www.crowdsec.net/blog/how-to-beat-application-ddos

They can be prone to small set of false positives, advise is to create a general brute force scenario that can be linked together using reprocess method.

**Comment by LaurenceJJones** [comment]
We added #848
