### ISSUE TITLE
dovecot slow brute force attacks - possible enhancement

### ISSUE THREAD

**Issue by dldewey** [crowdsecurity/hub#283]
Seeing an attack on Dovecot over the last few days that Crowdsec isn't able to help with in the default scenario. 
Looks like a script-based attack using many different IPs and networks against lists of non-existent usernames. The part that Crowdsec is missing is the slow speed of the attacks... the same IPs and netblocks appear over and over, but separated by large blocks of time, minutes/hours/days. With advice from @buixor I converted my bucket from leaky to trigger, and that picks them up and blocks on first occurrence, but still needs to block them over and over as these IPs recur. A different approach might be valuable to stop these slow but unrelenting attacks. In this particular case these are mostly standard, no-login built-in or non-existent accounts, but in the past I have seen similar attacks against true system users.

Here's a small sample of my logs from today:
Nov 11 01:18:41 hostname dovecot: auth-worker(16444): pam(testuser,203.159.80.190): unknown user
Nov 11 01:44:45 hostname dovecot: auth-worker(16697): pam(helpdesk,203.159.80.60): unknown user
Nov 11 02:02:22 hostname dovecot: auth-worker(16847): pam(scan,45.133.1.50): unknown user
Nov 11 02:06:03 hostname dovecot: auth-worker(16934): pam(marketing,45.144.225.205): unknown user
Nov 11 02:13:08 hostname dovecot: auth-worker(17035): pam(noreply,45.144.225.232): unknown user
Nov 11 02:14:20 hostname dovecot: auth-worker(17035): pam(prueba,45.144.225.115): unknown user
Nov 11 02:17:44 hostname dovecot: auth-worker(17118): pam(scanner,45.133.1.58): unknown user
Nov 11 02:22:53 hostname dovecot: auth-worker(17229): pam(copier,45.144.225.64): unknown user
Nov 11 02:31:04 hostname dovecot: auth-worker(17312): pam(test,45.133.1.127): unknown user
Nov 11 02:40:22 hostname dovecot: auth-worker(17440): pam(info,45.144.225.242): unknown user
Nov 11 03:04:48 hostname dovecot: auth-worker(18329): pam(webmaster,2.56.59.40): unknown user
Nov 11 03:08:02 hostname dovecot: auth-worker(18384): pam(auditor,37.0.11.164): unknown user
Nov 11 03:11:25 hostname dovecot: auth-worker(18419): pam(user1,37.0.10.49): unknown user
Nov 11 03:14:21 hostname dovecot: auth-worker(18466): pam(reception,45.133.1.109): unknown user
Nov 11 03:36:26 hostname dovecot: auth-worker(18891): pam(nagios,37.0.11.192): unknown user
Nov 11 03:37:55 hostname dovecot: auth-worker(19116): pam(demo,45.144.225.204): unknown user
Nov 11 03:42:13 hostname dovecot: auth-worker(19750): pam(postmaster,45.133.1.192): unknown user
Nov 11 03:48:48 hostname dovecot: auth-worker(20791): pam(finance,37.0.11.114): unknown user
Nov 11 03:58:43 hostname dovecot: auth-worker(20935): pam(printer,136.144.41.70): unknown user
Nov 11 04:05:30 hostname dovecot: auth-worker(21033): pam(admin,45.133.1.100): unknown user
Nov 11 04:10:18 hostname dovecot: auth-worker(21103): pam(teste,37.0.11.215): unknown user
Nov 11 04:12:40 hostname dovecot: auth-worker(21153): pam(test1,136.144.41.132): unknown user
Nov 11 04:40:13 hostname dovecot: auth-worker(21395): pam(spam,45.144.225.206): unknown user
Nov 11 04:42:07 hostname dovecot: auth-worker(21426): pam(guest,45.133.1.102): unknown user
Nov 11 04:42:48 hostname dovecot: auth-worker(21426): pam(accounts,136.144.41.87): unknown user
Nov 11 05:36:07 hostname dovecot: auth-worker(22684): pam(testuser,203.159.80.190): unknown user
Nov 11 05:39:58 hostname dovecot: auth-worker(22735): pam(scan,45.133.1.50): unknown user
Nov 11 06:05:22 hostname dovecot: auth-worker(23027): pam(scanner,45.133.1.58): unknown user
Nov 11 06:08:34 hostname dovecot: auth-worker(23027): pam(marketing,45.144.225.205): unknown user
Nov 11 06:18:08 hostname dovecot: auth-worker(23232): pam(temp,45.144.225.128): unknown user
Nov 11 06:31:10 hostname dovecot: auth-worker(23416): pam(helpdesk,203.159.80.60): unknown user
Nov 11 06:52:02 hostname dovecot: auth-worker(23681): pam(test,45.133.1.127): unknown user
Nov 11 07:00:24 hostname dovecot: auth-worker(23762): pam(info,45.144.225.242): unknown user
Nov 11 07:00:41 hostname dovecot: auth-worker(23762): pam(prueba,45.144.225.115): unknown user
Nov 11 07:12:38 hostname dovecot: auth-worker(24600): pam(copier,45.144.225.64): unknown user
Nov 11 07:20:16 hostname dovecot: auth-worker(24739): pam(noreply,45.144.225.232): unknown user
Nov 11 07:22:14 hostname dovecot: auth-worker(24785): pam(auditor,37.0.11.164): unknown user
Nov 11 08:11:28 hostname dovecot: auth-worker(25505): pam(reception,45.133.1.109): unknown user
Nov 11 08:28:41 hostname dovecot: auth-worker(25831): pam(demo,45.144.225.204): unknown user
Nov 11 08:32:04 hostname dovecot: auth-worker(25886): pam(webmaster,2.56.59.40): unknown user
Nov 11 08:40:01 hostname dovecot: auth-worker(26032): pam(teste,37.0.11.215): unknown user
Nov 11 08:50:55 hostname dovecot: auth-worker(26186): pam(nagios,37.0.11.192): unknown user
Nov 11 08:52:44 hostname dovecot: auth-worker(26255): pam(user1,37.0.10.49): unknown user
Nov 11 08:54:12 hostname dovecot: auth-worker(26297): pam(printer,136.144.41.70): unknown user
Nov 11 09:10:36 hostname dovecot: auth-worker(27282): pam(finance,37.0.11.114): unknown user
Nov 11 09:16:45 hostname dovecot: auth-worker(27384): pam(test1,136.144.41.132): unknown user
Nov 11 09:23:03 hostname dovecot: auth-worker(27384): pam(postmaster,45.133.1.192): unknown user
Nov 11 09:56:48 hostname dovecot: auth-worker(28563): pam(spam,45.144.225.206): unknown user
Nov 11 10:19:27 hostname dovecot: auth-worker(29057): pam(guest,45.133.1.102): unknown user
Nov 11 10:29:07 hostname dovecot: auth-worker(29240): pam(accounts,136.144.41.87): unknown user
Nov 11 10:35:17 hostname dovecot: auth-worker(29314): pam(admin,45.133.1.100): unknown user
Nov 11 10:51:30 hostname dovecot: auth-worker(29667): pam(scan,45.133.1.50): unknown user
Nov 11 11:02:28 hostname dovecot: auth-worker(29741): pam(testuser,203.159.80.190): unknown user
Nov 11 11:02:59 hostname dovecot: auth-worker(29741): pam(marketing,45.144.225.205): unknown user
Nov 11 11:06:06 hostname dovecot: auth-worker(29741): pam(scanner,45.133.1.58): unknown user
Nov 11 11:35:32 hostname dovecot: auth-worker(30500): pam(auditor,37.0.11.164): unknown user
Nov 11 11:42:49 hostname dovecot: auth-worker(31212): pam(info,45.144.225.242): unknown user
Nov 11 11:51:24 hostname dovecot: auth-worker(31404): pam(test,45.133.1.127): unknown user
Nov 11 12:02:30 hostname dovecot: auth-worker(31624): pam(prueba,45.144.225.115): unknown user
Nov 11 12:11:03 hostname dovecot: auth-worker(31913): pam(copier,45.144.225.64): unknown user
Nov 11 12:13:18 hostname dovecot: auth-worker(31913): pam(helpdesk,203.159.80.60): unknown user
Nov 11 12:37:06 hostname dovecot: auth-worker(32351): pam(teste,37.0.11.215): unknown user
Nov 11 12:37:14 hostname dovecot: auth-worker(32351): pam(noreply,45.144.225.232): unknown user
Nov 11 12:40:12 hostname dovecot: auth-worker(32432): pam(reception,45.133.1.109): unknown user
Nov 11 12:40:12 hostname dovecot: auth-worker(32432): pam(reception,45.133.1.109): unknown user
Nov 11 12:42:54 hostname dovecot: auth-worker(32490): pam(demo,45.144.225.204): unknown user
Nov 11 12:45:27 hostname dovecot: auth-worker(32538): pam(printer,136.144.41.70): unknown user
Nov 11 13:04:42 hostname dovecot: auth-worker(306): pam(test1,136.144.41.132): unknown user
Nov 11 13:07:09 hostname dovecot: auth-worker(477): pam(nagios,37.0.11.192): unknown user
Nov 11 13:19:39 hostname dovecot: auth-worker(691): pam(webmaster,2.56.59.40): unknown user
Nov 11 13:19:44 hostname dovecot: auth-worker(691): pam(finance,37.0.11.114): unknown user
Nov 11 13:30:18 hostname dovecot: auth-worker(874): pam(temp,45.144.225.128): unknown user
Nov 11 13:36:56 hostname dovecot: auth-worker(1021): pam(user1,37.0.10.49): unknown user

**Comment by buixor** [comment]
Are those exhaustive logs on the given period ? Because from the logs, each IP comes back every few (4-5) hours.
Even with very slow leakspeed, it might lead to some serious memory consumption, and having a "trigger" bucket like you did is likely too aggressive for common users.

**Comment by dldewey** [comment]
@buixor no, this was just a quick grep of 'unknown users' in that time frame. There's lots more traffic in between but for the IPs and particular error in question this is comprehensive. The trigger bucket works well for me since I only have a relatively small number of actual users to deal with (this is a high-traffic Mailman server, therefore mostly outbound). I certainly wouldn't want to trade memory issues for a leaky bucket solution.
