### ISSUE TITLE
parser or bouncer not functional for reference: pam_unix(sshd:auth): authentication failure

### ISSUE THREAD

**Issue by vincent1890** [crowdsecurity/hub#284]
Hello,

I’m new on crowdsec

I have a problem with parser ssh because it does not detect multiple attempts intrusions and connection testing on my server

Here are the log references that appear several times per second with multiple IPs or users and that are not blocked by crowdsec:par crowdsec : 
pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=8.218.14.36 user=root
pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=8.218.29.136 user=root
pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=209.141.52.25

Etc…

Like making all detect and block properly please.

Have a good day

**Comment by vincent1890** [comment]
For additional info crowdsec works well for some log reference other than the one previously mentioned because with the following command the result indicates a lot of ban already performed or in progress but not on the references of parser containing **pam_unix(sshd:auth): authentication failure;** apparently.

sudo cscli decisions list
|  ID   |  SOURCE  |    SCOPE:VALUE     |          REASON           | ACTION | COUNTRY |           AS           | EVENTS |     EXPIRATION      | ALERT ID |
| 41213 | crowdsec | Ip:82.157.27.246   | crowdsecurity/ssh-bf      | ban    | NL      |                        |      6 | 23h59m26.651560831s |     3680 |

**Comment by vincent1890** [comment]
Si j'utilise la commande qui permet de rajouter la règle avant la règle ouverture ssh 
`sudo ufw insert 1 deny from 8.218.0.0/16`

cela block correctement les IPs en cause et arrête les tentatives

**Comment by vincent1890** [comment]
sorry error closed

**Comment by he2ss** [comment]
Hi @vincent1890,

The logs you pasted are properly parsed. 
Following what you said, I think you didn't install a [bouncer](https://docs.crowdsec.net/docs/getting_started/install_crowdsec#install-a-bouncer), Is it the case ?
