### ISSUE TITLE
Parser's MD doesnt appear in Hub description

### ISSUE THREAD

**Issue by jusabatier** [crowdsecurity/hub#285]
The MD files for Apereo CAS doesn't appead in the Hub description.

For example, this MD : https://github.com/crowdsecurity/hub/blob/master/parsers/s01-parse/jusabatier/apereo-cas-audit-logs.md

Should appear in description here : https://hub.crowdsec.net/author/jusabatier/configurations/apereo-cas-audit-logs

Is it a misconfiguration problem ?

**Comment by buixor** [comment]
Hello,

The markdown was invalid, it was fixed here : https://github.com/crowdsecurity/hub/pull/287

Should be all good now :+1:
