### ISSUE TITLE
Traefik collection cannot be installed

### ISSUE THREAD

**Issue by rkokkelk** [crowdsecurity/hub#321]
I'm really looking forward to install the Traefik collection, however every time I run: `cscli collections install crowdsecurity/traefik`, I get `unable to retrieve item : crowdsecurity/traefik`. 

Even when I'm successfully executing `cscli hub update`, it still does not identify the traefik collection. It's also not mentioned in the: `/etc/crowdsec/hub/.index.json`, do you guys have any suggestion.

Also, thanks everybody for this awesome software.

**Comment by buixor** [comment]
Hello @rkokkelk !

Which version of crowdsec are you running ?

The hub is versioned, so if you're running a version that is anterior to the collection's release (ie. < 1.2.1), you might not be able to get it unless you upgrade (or we backport, or you deploy manually). While this might be a bit restrictive it's to ensure we don't break older setups :smile: 

Please let me know !

**Comment by rkokkelk** [comment]
Ah check, I'm running a docker container build in 18/11/2021 (crowdsecurity/crowdsec:latest@sha256:02bb6118aa0a4cb6e50ba04abc19f3032ae72c0a5e7bd2b7c3d0c7e5a3aac531@sha256:66f3408d4c4b5bd15a9a149a8f676be54327e4ec797584a8df5a9b1f8d490de3)

```bash
/ # cscli version
2021/12/21 19:45:03 version: v1.2.1-dd03d073558e380c283afe66942f537c3da647ff
2021/12/21 19:45:03 Codename: alphaga
```

Is there any documentation on either the hub or from the logging in order to check if I've got the correct version running?

**Comment by AlteredCoder** [comment]
Hello @rkokkelk ,

In https://hub.crowdsec.net/browse/#collections or https://hub.crowdsec.net/browse/#configurations, you can select your crowdsec version and check which collection/configuration are available for a specific crowdsec version

**Comment by rkokkelk** [comment]
Thank you for your recommendations, however, as previously specified I was  running `1.2.1`, currently updated to `1.2.2` but the issue still persist. I cannot install the traefik collection because I get the following error:

```bash
/ # cscli hub update
INFO[25-12-2021 04:41:38 PM] Wrote new 83897 bytes index to /etc/crowdsec/hub/.index.json 
/ # cscli collections install crowdsecurity/traefik
FATA[25-12-2021 04:41:39 PM] unable to retrieve item : crowdsecurity/traefik 
```

**Comment by rkokkelk** [comment]
Okay, delving into the source code I've finally boiled down to me copying an old configuration file from an online source which contained an old entry for the config:
```yaml
cscli:
   hub: wip_lapi
```

Changing it to master resolved my issue. However, additional logging could have definitely helped from a debugging side of view. Just stating which hub branch is used might have helped me resolving this a few days ago and hopefully prevents user from delving into the source code to debug it. 

Thanks again for your guys help and this amazing product. Have a nice Christmas weekend.
