### ISSUE TITLE
File compressions & their extensions

### ISSUE THREAD

**Issue by bennet-esyoil** [crowdsecurity/hub#329]
When using compression on resource-files like css and js, the resulting filename can be `style.css.gz`. This is currently not detected as a resource, resulting in them being analyzed as a normal request, which results (for us) in false-positives. 

It would be nice if such resources would also be filtered out and not be analyzed. Same goes for `.brotli` extensions. 

Thanks :)

See PR #330 

Before and after screenshot:
![Screenshot from 2021-12-30 10-07-30](https://user-images.githubusercontent.com/48118908/147737605-6d54c367-f7e7-402e-b9b3-56a334cb6cff.png)

**Comment by he2ss** [comment]
Hi @bennet-esyoil,

Thanks for you contribution, it was merged. 
You can now close this issue.

**Comment by bennet-esyoil** [comment]
@he2ss thank you!
