### ISSUE TITLE
High CPU usage when using the `http-bad-user-agent` scenario

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/hub#334]
The `http-bad-user-agent` uses regexp to mach the user-agent, but with high traffic, this leads to very high CPU usage.

The culprit seems to be our use of `matches` in the expr, which does not compile the regexp ahead of time.

We should implement regex compilation in `RegexpInFile` and use that instead.

**Comment by buixor** [comment]
this has been fixed with 1.3.1 and the introduction of https://github.com/crowdsecurity/hub/blob/master/scenarios/crowdsecurity/http-bad-user-agent.yaml
