### ISSUE TITLE
Wordpress scenario: Detect abuse of 's=' parameter

### ISSUE THREAD

**Issue by klausagnoletti** [crowdsecurity/hub#344]
I'd like to suggest that the wordpress scenario should be able to support abuse of the 's=' parameter since this could be abused for a DDoS attack.

**Comment by buixor** [comment]
Can you provide more context on what should be detected or done with it ?

**Comment by klausagnoletti** [comment]
No, not 4 months later :-) I remember someone saying that but I have no idea where and I can't find it again. So note to self: write more metadata in issues :-)
