### ISSUE TITLE
Support for containerd logs

### ISSUE THREAD

**Issue by stskrp** [crowdsecurity/hub#356]
Hello,
There is a parser for docker logs, which are in json format.
Would it be possible to implement parser for **containerd** logs also which are not in json format?

**Comment by he2ss** [comment]
Hi @stskrp,

This [PR](https://github.com/crowdsecurity/hub/pull/362) was merged.
Could you please try with this new parser : https://hub.crowdsec.net/author/crowdsecurity/configurations/cri-logs

**Comment by stskrp** [comment]
Hello,
just tried, works as expected, thank you :)
