### ISSUE TITLE
traefik-logs parser verb or method

### ISSUE THREAD

**Issue by tuxtof** [crowdsecurity/hub#394]
i find an issue in the traefik-logs parser v0.1

trying to parse a GET call

if i use JSON log format

GET are stored in evt.Parsed.verb

but if i use Common  Log Format

GET are stored in evt.Parsed.method

who failed against some evt.Parsed.verb scenario like http-crawl-non_statics or http-open-proxy who is using evt.Parsed.verb

**Comment by Dominic-Wagner** [comment]
So all the Basic HTTP Scenarios are looking into evt.Parsed.verb.
I noticed that not only Traefik CLF uses a different name (method), haproxy, iis and caddy are also having the same problem, as they use http_verb. 
So its inconsistent all over the hub.

**Comment by woopstar** [comment]
Apache does not even have verb

**Comment by Dominic-Wagner** [comment]
@woopstar 
Apache2 does contain the request method. Its inside the pattern COMMONAPACHELOG. See [Crowdsec Docs](https://github.com/crowdsecurity/crowdsec-docs/blob/main/crowdsec-docs/docs/parsers/patterns-documentation.md#commonapachelog) for that.
Apache is using CLF by standard which includes the method(here called verb).

**Comment by he2ss** [comment]
Hi,

Forgot to reply on this issue. It's was fixed with this https://github.com/crowdsecurity/hub/pull/414.
