### ISSUE TITLE
Enhancement: Add a forward_dns() method

### ISSUE THREAD

**Issue by Athanasius** [crowdsecurity/hub#405]
After tearing my hair out for a few hours trying to figure out how I'd do this with current crowdsec I finally realised how the rdns parser works and that extra Go code would need adding to add a `forward_dns` method to complement the `reverse_dns` method in `pkg/parser/enrich_dns.go`.

I'd like to be able to reference the IP that a DNS name resolves to in some crowdsec configuration.  Relying on a local data source via `File()` quickly runs into file permission and/or "this will only update periodically" issues.

My actual use case is wanting to whitelist an IP that is maintained in some dynamic DNS.  In this case we very definitely control the DNS record in question (it's in a local-master zone, and the update is done using nsupdate and a secure key).  Getting that IP into a file that could be a data source will be a pain due to file ownership/permissions (we do use nsnotifyd to commit the zone changes to git, but that runs as its own user, so won't be able to write to /var/lib/crowdsec/data).

I have zero experience of writing Go code and no time to get up to speed on it.  I wouldn't want to naively copy what's there for `reverse_dns` without realising caveats and gotchas.  For instance the method likely needs to return an array, in case the DNS label in question has multiple records.

**Comment by LaurenceJJones** [comment]
1.4.2 will have LookupHost('my-home-domain.invalid') which will return a [] string that is known to the local resolver. We advise this is use in port overflow scenarios since it will be very slow.
