### ISSUE TITLE
Caddy v2.5.0 to remove common log

### ISSUE THREAD

**Issue by PhasecoreX** [crowdsecurity/hub#408]
Based on https://github.com/caddyserver/caddy/issues/4148, it seems like the common log part of the Caddy logs will be removed once v2.5.0 is released. It looks like this is used for some part of the Caddy parser [here](https://github.com/crowdsecurity/hub/blob/master/parsers/s01-parse/crowdsecurity/caddy-logs.yaml), so just wanted to bring this up beforehand.

**Comment by BlackRa1nFR** [comment]
Hello, problem with crowdsec here and caddy log, can you update the caddy parser ? thanks

**Comment by burgerlander** [comment]
Is this still being maintained? Not rushing the maintainer or anything, it just seems like there has been no response to this issue, nor the pull request that's linked here.

**Comment by Lednerb** [comment]
With the latest release and https://github.com/crowdsecurity/crowdsec/pull/1576 it should be possible to implement an optimized approach for parsing the newer caddy logs.
