### ISSUE TITLE
whitelists.yaml error

### ISSUE THREAD

**Issue by stratege1401** [crowdsecurity/hub#416]
Installed from https://hub.crowdsec.net/author/crowdsecurity/configurations/whitelists `cscli parsers install crowdsecurity/whitelists`

my file:

> description: "Whitelist events from private ipv4 addresses"
> whitelist:
>   reason: "private ipv4/ipv6 ip/ranges"
>   ip:
>     - "127.0.0.1"
>     - "privacy"
>  cidr:
>     - "192.168.1.0/34"

after `systemctl reload crowdsec` or a regular stop/start i get the following error:

msg="Error decoding parsing configuration file '/etc/crowdsec/parsers/s02-enrich/whitelists.yaml': yaml: line 7: did not find expected key"

**Comment by buixor** [comment]
Hello @stratege1401 

It seems the yaml is invalid, did you let a space slip a the beginning on the `cidr` line ? :wink:

**Comment by stratege1401** [comment]
space slip or not, i did a `cscli parsers install crowdsecurity/whitelists`

Then, i changed to my value ( notice my first cidr value was wrong ).

Now, it seem to work....
