### ISSUE TITLE
http-probing banning 192.168.1.254

### ISSUE THREAD

**Issue by stratege1401** [crowdsecurity/hub#417]
i have no clue.... had to cscli delete -i 192.168.1.254 to regain http and ssh access to my server.... ( before adding ip whitelist )

**Comment by buixor** [comment]
@stratege1401 hello,

Can you give a bit more context so we can help ?
Do you know which scenario it triggered ? (`cscli decisions list` or `cscli alerts list` ?) Maybe inspect the associated alert to get more context ? (`cscli alerts inspect -d <alert_id>`)

**Comment by stratege1401** [comment]
for unknow reason, crowdsec acted like whitelist was desable.... 

after a `cscli -f parsers install crowdsecurity/whitelists`  ( -f because i had manually altered the whitelist, so appear has tainted ) things are now back to normal...
