### ISSUE TITLE
proftpd collection

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/hub#43]
- proftpd parser :

```
Nov 3 14:51:38 proftpd: pam_unix(proftpd:auth): authentication failure; logname= uid=0 euid=0 tty=/dev/ftpd27769 ruser=www-data rhost=1.2.3.4 user=www-data
```

 - proftpd scenario : bruteforce (heavily inspired from ssh-bf and such)

**Comment by blotus** [comment]
Those logs are directly from PAM, we do no want to use them for proftpd, as it supports other authentication backends.
There are 2 kinds of logs (i still need to make sure they stay consistent when another backend is in use):
 - Bad username: `2021-05-28 12:28:41,327 mantis proftpd[404760] mantis (localhost[127.0.0.1]): USER asd: no such user found from localhost [127.0.0.1] to ::ffff:127.0.0.1:21`
 - Bad password: `2021-05-28 12:28:49,966 mantis proftpd[404789] mantis (localhost[127.0.0.1]): USER seb (Login failed): Incorrect password`
