### ISSUE TITLE
crowdsecurity/http-probing : Exclude static ressources

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/hub#44]
the scenario `crowdsecurity/http-probing` should exclude static ressources to avoid FP.

**Comment by ririsoft** [comment]
Isn't it the case already ?
https://github.com/crowdsecurity/hub/blob/master/scenarios/crowdsecurity/http-probing.yaml#L6
I do not understand your point, sorry.

**Comment by buixor** [comment]
yes, this has been dealt with, the http parser was missing some static ressources extensions.
