### ISSUE TITLE
endlessh: parser fails in ipv4-only setups

### ISSUE THREAD

**Issue by thespad** [crowdsecurity/hub#445]
If endlessh is configured to only bind to IPv4 then the log format is
```
2022-04-16T15:06:56.918Z ACCEPT host=178.128.199.192 port=42832 fd=4 n=1/4096
```
Instead of
```
2022-04-16T15:14:17.341Z ACCEPT host=::ffff:129.151.93.41 port=42006 fd=4 n=1/4096
```
And therefore doesn't match
```
ENDLESSH_ACCEPT_V4: "%{TIMESTAMP_ISO8601:timestamp} ACCEPT host=::ffff:%{IPV4:source_ip} "
```

**Comment by LaurenceJJones** [comment]
Updated the PR to support optional `(::ffff:)?` syntax. Could we get some feedback on this? I have tested it want to make sure the other ipv6 change was needed.

**Comment by thespad** [comment]
I'll try and give it a test this week
