### ISSUE TITLE
Add Pinterest to Whitelist / Good Actors

### ISSUE THREAD

**Issue by ThomasLohner** [crowdsecurity/hub#45]
crawl-xxx-xxx-xxx-xxx.pinterest.com (xxx being the actual ip) should be allowed as a good actor. If not `crowdsecurity/http-probing` will block this ip.

**Comment by registergoofy** [comment]
I added pinterest /24 to the ip whitelist. With a postoverflows update you should get it too.

Thanks for the feedback
