### ISSUE TITLE
Improved home-assistant parsing

### ISSUE THREAD

**Issue by RoboMagus** [crowdsecurity/hub#451]
I've found CrowdSec a massive improvement over HomeAssistants internal IP-Ban component, however by lack of additional information it can still be a problem to setup bariers strict enough to block malicious attempts but can be lenient against the existing issues (e.g. invalid authentication by the camera-proxy).

To get the additional info in the HomeAssistant logging for parsing I've opened up this [pull request](https://github.com/home-assistant/core/pull/70285) for the HomeAssistant core. Hoping this gets through, the grok parser here should also be updated.

The expanded log entry would become:
```Login attempt or request with invalid authentication from {remote_host} ({remote_addr}). ({user_agent}) path: '{request.path}', username: '{username}'```

Happy to also do that myself and create a PR for it, 
I'm just now checking ahead if the current grok line would be resilient against such format changes.

And perhaps get some additional ideas to also add to the auth. failure logging in HA while I'm at it..

**Comment by he2ss** [comment]
Hi @RoboMagus,

Following the [current HA parser](https://hub.crowdsec.net/author/crowdsecurity/configurations/home-assistant-logs), it catch the user-agent, so if you are able to craft the user-agent from the camera-proxy. It can be already usefull to help avoid be banning this authentication attempts.
When you PR will be merged, we can of course update the grok to support the new log format, so the grok will support both new and old format.

Maybe you already know, but we create [crowdsec addon](https://github.com/crowdsecurity/home-assistant-addons) you can install to detect those attacks and raise alerts.
For the blocking part, we're waiting for some features (already merged and will be available in HA OS 8.0) to release the [crowdsec firewall bouncer addon](https://github.com/crowdsecurity/home-assistant-addons/pull/2).

**Comment by RoboMagus** [comment]
I've indeed something about a crowdsec addon when scrolling through my feeds. Getting this to the masses in a user friendly addon seems a good idea. Not for me though as I'm running everything purely in docker (unsupervised).

For the camera proxy issue, this seems not to be restricted to the companion app and as such would not really fix the issue. Having more lenient rules for all traffic from the companion app also does not really feel right either. Though to be fair, it's not a very likely attack vector that requires much attention.

Hence, having more information available to parse seems to be the better solution. But indeed both forward and backward compatibility should be considered.

I am curious about the 'raising alerts' part of the addon though, so I'll take a good look at that in your codebase to see if that's something I can also use to get notified through HomeAssistant of crowdsec events. I'm currently using a workaround that uses the HTTP post notifier which is then translated into MQTT before being picked up by HA. A more integrated solution would be an improvement for my setup :)

**Comment by RoboMagus** [comment]
PR home-assistant/core#75218 got merged. This contains a different format, but at least finally additional information is provided.

Log entry format example:
`Login attempt or request with invalid authentication from example.com (200.201.202.204). Requested URL: '/example'.`

**Comment by a1ad** [comment]
@RoboMagus is this the reason why the current parser is not working for me?

Parser installed:
 crowdsecurity/home-assistant-logs        ✔️ enabled   0.5       /etc/crowdsec/parsers/s01-parse/home-assistant-logs.yaml     

Metrics:
                     Source                      | Lines read | Lines parsed | Lines unparsed | Lines poured to bucket |
+-------------------------------------------------+------------+--------------+----------------+------------------------+
| file:/var/logs/homeassistant/home-assistant.log | 619        | -            | 619            | -                      |

Log entry that should be parsed:
 Login attempt or request with invalid authentication from ***Requested URL: '/auth/login_flow/1eabc576e87baf5bf75578bc0e626b3d'. (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0)
