### ISSUE TITLE
.env scanner http scenario

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/hub#455]
Seeing some IPs scanning for `.env` file, like :

```
/developer/.env
/api/.env
/prod/.env
/stag/.env
/localhost/.env
/dev/.env
/production/.env
/platform/.env
/test/.env
/app/.env
/locally/.env
/development/.env
...
```

**Comment by he2ss** [comment]
Already supported by [this scenario](https://github.com/crowdsecurity/hub/blob/master/scenarios/crowdsecurity/http-sensitive-files.yaml), using [this datafile](https://raw.githubusercontent.com/crowdsecurity/sec-lists/master/web/sensitive_data.txt)
