### ISSUE TITLE
Google Bot new Domain?

### ISSUE THREAD

**Issue by ThomasLohner** [crowdsecurity/hub#46]
We see traffic from `google-proxy-xxx-xxx-xxx-xxx.google.com` (xxx being the actual ip) that is blocked by `crowdsecurity/http-probing`. So far i can not not find any documentation if this is a legitimate google bot domain or not. 

Here it only states "crawl-" and "rate-limited-proxy" ... but who knows ;-) https://support.google.com/webmasters/answer/80553?hl=en

**Comment by registergoofy** [comment]
For now this shouldn't be happen if you install the `crowdsecurity/rdns` and `crowdsecurity/seo-bots-whitelist` postoverflows.

You can do this by:
```
cscli install postoverflow crowdsecurity/rdns
cscli install postoverflow crowdsecurity/seo-bots-whitelist
```
What I understand from the link you shared, is that we should let all *.googlebot.com and *.google.com pass if and only if we check back the forward dns of the reverse dns we get from the offending IP.

But you are right to highlight this, this mechanism we introduced with these two postoverflows is not sufficient: we only get the reverse dns and we don't check the result again with forward dns. I just added this task for the near future.
