### ISSUE TITLE
Improvement/Patterns: make tcpdump_output recognize IPv6 logs

### ISSUE THREAD

**Issue by basbebe** [crowdsecurity/hub#469]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently [tcpdump_output](https://docs.crowdsec.net/docs/next/parsers/patterns/#tcpdump_output) only recognizes IPv4-addresses

**Describe alternatives you've considered** (Optional) 
–

**Example of what you imagine**
```
%{GREEDYDATA:timestamp} IP(6)? %{IPORHOST:source_ip}\.%{INT:source_port} > %{IPORHOST:dest_ip}\.%{INT:dest_port}: Flags \[%{GREEDYDATA:tcpflags}\], seq
```

**Additional context**

**Comment by he2ss** [comment]
Hi @basbebe,

Could you please provide some samples logs including IPv6.

**Comment by LaurenceJJones** [comment]
Just adding a comment to remind @basbebe could you provide logs with an ipv6 address??

**Comment by LaurenceJJones** [comment]
Please reopen when you can provide logs
