### ISSUE TITLE
Modsec collection content has an error

### ISSUE THREAD

**Issue by nickchomey** [crowdsecurity/hub#487]
https://hub.crowdsec.net/author/crowdsecurity/collections/modsecurity
The two cards at the bottom are duplicates - they both are for the modsec parser. But the collection seems to be comprised of a collection and scenario. 

![image](https://user-images.githubusercontent.com/88559987/173194959-9a094f5a-f85c-40c4-bc4e-c2c9887b97bd.png)

**Comment by LaurenceJJones** [comment]
New hub has made this more defined, please check and reopen if not explicit
