### ISSUE TITLE
better haproxy bouncer ?

### ISSUE THREAD

**Issue by aderumier** [crowdsecurity/hub#493]
Hi,

I was looking at the current haproxy bouncer

https://github.com/hellracer/cs-haproxy-bouncer

The implementation is pretty basic,  it's calling local api for each http request coming to haproxy.

so, it could be a bottleneck or impact performance on high loaded haproxy server.

I think it could be better to have some kind of daemon , to sync crowdsec the local api  to an haproxy acl or stick-table.

haproxy have a simple runtime api:

https://www.haproxy.com/blog/dynamic-configuration-haproxy-runtime-api/

(I don't have the skill to write a clean golang daemon, but it could be easy to do with a simple bash cron,calling to localapi, and writing to the haproxy socket)

BTW, I have a written some year ago a haproxy lua script, to manage captcha/challenge

https://github.com/aderumier/haproxy-botnetchallenge

it could be adapted to remove ip from local api on success and have same catpcha feature than nginx bouncer.

**Comment by aderumier** [comment]
I think a basic dirty implementation could be simply to use 
the crowdsec-custom-bouncer.service

and calling a script bash script writing to haproxy socket to fill a blacklist acl.

BTW, another 2 cool project to implement captcha in haproxy in lua

https://github.com/mora9715/haproxy_ddos_protector/
https://gitgud.io/fatchan/haproxy-protection

(better than my lua script)

**Comment by LaurenceJJones** [comment]
👀 keep an eye out on this? https://github.com/crowdsecurity/cs-haproxy-bouncer 👀

**Comment by LaurenceJJones** [comment]
Bouncer is out! Closing this comment #572

**Comment by aderumier** [comment]
Hi, I'm going to test it next week.  I have upgraded all my production to haproxy 2.6, so I'm compatible now.

**Comment by LaurenceJJones** [comment]
Great! Please let us know and if you experience any issues drop an issue on https://github.com/crowdsecurity/cs-haproxy-bouncer
