### ISSUE TITLE
Windows Firewall Parsers fails

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/hub#509]
Crowdsec Version: 1.4-RC4
```
2022/07/12 21:34:49 version: v1.4.0-rc4-73f336363a4705249e28007db54fb9d3d6780745
2022/07/12 21:34:49 Codename: alphaga
2022/07/12 21:34:49 BuildDate: 2022-07-11_11:44:08
2022/07/12 21:34:49 GoVersion: 1.17.9
2022/07/12 21:34:49 Platform: windows
2022/07/12 21:34:49 Constraint_parser: >= 1.0, <= 2.0
2022/07/12 21:34:49 Constraint_scenario: >= 1.0, < 3.0
2022/07/12 21:34:49 Constraint_api: v1
2022/07/12 21:34:49 Constraint_acquis: >= 1.0, < 2.0
```
Windows server version: Microsoft Windows Server 2019 Standard Evaluation | Build:  17763.3046
Example Log Input
```
2022-07-11 21:03:39 DROP TCP 192.168.122.1 192.168.122.71 43286 135 60 S 3362791310 0 64240 - - - RECEIVE
2022-07-11 21:03:39 DROP TCP 192.168.122.1 192.168.122.71 52098 139 60 S 3387349162 0 64240 - - - RECEIVE
2022-07-11 21:03:39 DROP TCP 192.168.122.1 192.168.122.71 51426 445 60 S 896008114 0 64240 - - - RECEIVE
2022-07-11 21:03:40 DROP TCP 192.168.122.1 192.168.122.71 51426 445 60 S 896008114 0 64240 - - - RECEIVE
2022-07-11 21:03:40 DROP TCP 192.168.122.1 192.168.122.71 52098 139 60 S 3387349162 0 64240 - - - RECEIVE
2022-07-11 21:03:40 DROP TCP 192.168.122.1 192.168.122.71 43286 135 60 S 3362791310 0 64240 - - - RECEIVE
2022-07-11 21:03:54 DROP TCP 192.168.122.1 192.168.122.71 53978 47001 60 S 288201912 0 64240 - - - RECEIVE
2022-07-11 21:03:55 DROP TCP 192.168.122.1 192.168.122.71 53978 47001 60 S 288201912 0 64240 - - - RECEIVE
2022-07-11 21:03:56 DROP TCP 192.168.122.1 192.168.122.71 34954 49666 60 S 596170976 0 64240 - - - RECEIVE
2022-07-11 21:03:56 DROP TCP 192.168.122.1 192.168.122.71 58088 49664 60 S 2852058020 0 64240 - - - RECEIVE
2022-07-11 21:03:56 DROP TCP 192.168.122.1 192.168.122.71 55526 49669 60 S 1004765200 0 64240 - - - RECEIVE
2022-07-11 21:03:56 DROP TCP 192.168.122.1 192.168.122.71 36318 49665 60 S 2166476115 0 64240 - - - RECEIVE
2022-07-11 21:03:56 DROP TCP 192.168.122.1 192.168.122.71 59712 49670 60 S 2315743546 0 64240 - - - RECEIVE
2022-07-11 21:03:56 DROP TCP 192.168.122.1 192.168.122.71 34768 49667 60 S 3657526399 0 64240 - - - RECEIVE
2022-07-11 21:03:56 DROP TCP 192.168.122.1 192.168.122.71 34522 49671 60 S 1200233265 0 64240 - - - RECEIVE
2022-07-11 21:03:56 DROP TCP 192.168.122.1 192.168.122.71 48854 49668 60 S 3520079752 0 64240 - - - RECEIVE
2022-07-11 21:03:57 DROP TCP 192.168.122.1 192.168.122.71 34522 49671 60 S 1200233265 0 64240 - - - RECEIVE
2022-07-11 21:03:57 DROP TCP 192.168.122.1 192.168.122.71 59712 49670 60 S 2315743546 0 64240 - - - RECEIVE
2022-07-11 21:03:57 DROP TCP 192.168.122.1 192.168.122.71 55526 49669 60 S 1004765200 0 64240 - - - RECEIVE
2022-07-11 21:03:57 DROP TCP 192.168.122.1 192.168.122.71 34954 49666 60 S 596170976 0 64240 - - - RECEIVE
2022-07-11 21:03:57 DROP TCP 192.168.122.1 192.168.122.71 48854 49668 60 S 3520079752 0 64240 - - - RECEIVE
2022-07-11 21:03:57 DROP TCP 192.168.122.1 192.168.122.71 34768 49667 60 S 3657526399 0 64240 - - - RECEIVE
2022-07-11 21:03:57 DROP TCP 192.168.122.1 192.168.122.71 36318 49665 60 S 2166476115 0 64240 - - - RECEIVE
2022-07-11 21:03:57 DROP TCP 192.168.122.1 192.168.122.71 58088 49664 60 S 2852058020 0 64240 - - - RECEIVE
```

Installed Collections
```
 crowdsecurity/windows           ✔️  enabled  0.1      C:\ProgramData\CrowdSec\config\collections\windows.yaml
 crowdsecurity/windows-firewall  ✔️  enabled  0.1      C:\ProgramData\CrowdSec\config\collections\windows-firewall.yaml
```
cscli metrics
```
time="12-07-2022 09:05:02 PM" level=info msg="Acquisition Metrics:"
+---------------------------------------------------------------+------------+--------------+----------------+------------------------+
|                            SOURCE                             | LINES READ | LINES PARSED | LINES UNPARSED | LINES POURED TO BUCKET |
+---------------------------------------------------------------+------------+--------------+----------------+------------------------+
| file:C:\\Windows\\System32\\LogFiles\\Firewall\\pfirewall.log | 10         | -            | 10             | -                      |
+---------------------------------------------------------------+------------+--------------+----------------+------------------------+
time="12-07-2022 09:05:02 PM" level=info msg="Parser Metrics:"
+------------------------------------+------+--------+----------+
|              PARSERS               | HITS | PARSED | UNPARSED |
+------------------------------------+------+--------+----------+
| crowdsecurity/windows-non-eventlog | 10   | 10     | -        |
+------------------------------------+------+--------+----------+
time="12-07-2022 09:05:02 PM" level=info msg="Local Api Metrics:"
+--------------------+--------+------+
|       ROUTE        | METHOD | HITS |
+--------------------+--------+------+
| /v1/heartbeat      | GET    | 9    |
| /v1/watchers/login | POST   | 2    |
+--------------------+--------+------+
time="12-07-2022 09:05:02 PM" level=info msg="Local Api Machines Metrics:"
+--------------------------------------------------+---------------+--------+------+
|                     MACHINE                      |     ROUTE     | METHOD | HITS |
+--------------------------------------------------+---------------+--------+------+
| 2cdf944014ae49b7b7a64f6e57a0e50eybfwV8j8wXut54rp | /v1/heartbeat | GET    | 9    |
+--------------------------------------------------+---------------+--------+------+
time="12-07-2022 09:05:02 PM" level=info msg="Local Api Decisions:"
+-----------------------------------------+--------+--------+-------+
|                 REASON                  | ORIGIN | ACTION | COUNT |
+-----------------------------------------+--------+--------+-------+
| crowdsecurity/iptables-scan-multi_ports | CAPI   | ban    | 3627  |
| crowdsecurity/windows-bf                | CAPI   | ban    | 1098  |
+-----------------------------------------+--------+--------+-------+

```

**Comment by blotus** [comment]
Hello,

This issue is already fixed in the parser.

Can you try to run `cscli.exe hub update` and `cscli.exe collections upgrade crowdsecurity/windows-firewall` and restart the service?

When did you install the RC? Was it an upgrade from 1.3.3?

**Comment by LaurenceJJones** [comment]
Fresh installed the RC as I was helping a user with an issue. I ran both of them yesterday plus again just in case anything has changed but still getting failing to parse.

Here is my local parser pattern
```

```

**Comment by LaurenceJJones** [comment]
[parser works](https://grokdebugger.com?pattern=%25%7BTIMESTAMP_ISO8601%3Adate%7D%20DROP%20TCP%20%25%7BIP%3Asrc_ip%7D%20%25%7BIP%3Adst_ip%7D%20%25%7BINT%3Asrc_port%7D%20%25%7BINT%3Adst_port%7D%20%25%7BINT%3Asize%7D%20%25%7BWORD%3Aflags%7D%20%25%7BINT%3Atcpsyn%7D%20%25%7BINT%3Atcpack%7D%20%25%7BINT%3Awindow%7D%20-%20-%20-%20RECEIVE(%20%25%7BINT%3Apid%7D)%3F&sample=2022-07-11%2021%3A03%3A39%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2043286%20135%2060%20S%203362791310%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A39%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2052098%20139%2060%20S%203387349162%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A39%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2051426%20445%2060%20S%20896008114%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A40%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2051426%20445%2060%20S%20896008114%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A40%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2052098%20139%2060%20S%203387349162%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A40%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2043286%20135%2060%20S%203362791310%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A54%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2053978%2047001%2060%20S%20288201912%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A55%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2053978%2047001%2060%20S%20288201912%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A56%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2034954%2049666%2060%20S%20596170976%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A56%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2058088%2049664%2060%20S%202852058020%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A56%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2055526%2049669%2060%20S%201004765200%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A56%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2036318%2049665%2060%20S%202166476115%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A56%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2059712%2049670%2060%20S%202315743546%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A56%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2034768%2049667%2060%20S%203657526399%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A56%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2034522%2049671%2060%20S%201200233265%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A56%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2048854%2049668%2060%20S%203520079752%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A57%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2034522%2049671%2060%20S%201200233265%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A57%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2059712%2049670%2060%20S%202315743546%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A57%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2055526%2049669%2060%20S%201004765200%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A57%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2034954%2049666%2060%20S%20596170976%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A57%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2048854%2049668%2060%20S%203520079752%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A57%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2034768%2049667%2060%20S%203657526399%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A57%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2036318%2049665%2060%20S%202166476115%200%2064240%20-%20-%20-%20RECEIVE%0A2022-07-11%2021%3A03%3A57%20DROP%20TCP%20192.168.122.1%20192.168.122.71%2058088%2049664%2060%20S%202852058020%200%2064240%20-%20-%20-%20RECEIVE)

**Comment by Crush33** [comment]
Hi

same issue 
https://cdn.discordapp.com/attachments/1007382595107029033/1007382595388055674/unknown.png

here are some firewall log sample :
```
#Version: 1.5
#Software: Microsoft Windows Firewall
#Time Format: Local
#Fields: date time action protocol src-ip dst-ip src-port dst-port size tcpflags tcpsyn tcpack tcpwin icmptype icmpcode info path

2022-08-13 07:26:52 ALLOW ICMP 10.21.23.35 10.12.13.14 - - 0 - - - - 8 0 - RECEIVE
2022-08-13 07:26:52 DROP TCP 94.232.47.52 10.12.13.14 28126 3390 52 S 607837051 0 8192 - - - RECEIVE
2022-08-13 07:26:52 DROP TCP 91.240.242.201 10.12.13.14 47700 3390 52 S 3597459876 0 8192 - - - RECEIVE
2022-08-13 07:26:54 DROP TCP 91.240.242.201 10.12.13.14 7227 3390 52 S 2575337906 0 8192 - - - RECEIVE
2022-08-13 07:26:55 DROP TCP 94.232.47.52 10.12.13.14 28126 3390 52 S 607837051 0 8192 - - - RECEIVE
2022-08-13 07:26:55 DROP TCP 109.107.166.74 10.12.13.14 36054 3390 48 S 2107129952 0 8192 - - - RECEIVE
2022-08-13 07:26:56 DROP TCP 109.107.166.71 10.12.13.14 7775 3390 48 S 4070220230 0 8192 - - - RECEIVE
2022-08-13 07:26:56 DROP TCP 109.107.166.74 10.12.13.14 32337 3390 52 S 3878060041 0 8192 - - - RECEIVE
```

and my parser :
```onsuccess: next_stage
filter: "evt.Parsed.program == 'windows-firewall' and evt.Parsed.message contains ' DROP TCP ' and evt.Parsed.message contains ' RECEIVE '"
name: crowdsecurity/windows-firewall-logs
description: "Parse windows firewall drop logs"
grok:
  pattern: "%{TIMESTAMP_ISO8601:date} DROP TCP %{IP:src_ip} %{IP:dst_ip} %{INT:src_port} %{INT:dst_port} %{INT:size} %{WORD:flags} %{INT:tcpsyn} %{INT:tcpack} %{INT:window} - - - RECEIVE( %{INT:pid})?" 
  apply_on: message
statics:
    - meta: service
      value: tcp
    - meta: log_type
      value: iptables_drop
    - meta: source_ip
      expression: "evt.Parsed.src_ip"
    - target: evt.StrTime
      expression: evt.Parsed.date
```

**Comment by Crush33** [comment]
PS C:\Windows\system32> cscli explain --log "2022-09-12 12:57:01 DROP TCP 92.255.85.111 11.111.11.11 62065 3390 52 S 4222345295 0 64240 - - - RECEIVE" --type windows-firewall
line: 2022-09-12 12:57:01 DROP TCP 92.255.85.111 11.111.11.11 62065 3390 52 S 4222345295 0 64240 - - - RECEIVE
        ├ s00-raw
        |       ├ 🔴 crowdsecurity/windows-eventlog
        |       └ 🟢 crowdsecurity/windows-non-eventlog (first_parser)
        ├ s01-parse
        |       ├ 🔴 crowdsecurity/windows-auth
        |       └ 🔴 crowdsecurity/windows-firewall-logs
        └-------- parser failure 🔴

**Comment by chalvorson** [comment]
Using a fresh install of v1.4.1 on Windows Server 2016, I'm seeing the same behavior reported by the others.  I noticed that our firewall logs do not have the pid at the end of line, but the filter line assumes there will be a space after RECEIVE.

In the file, **windows-firewall-logs.yaml,** I removed the space after RECEIVE in the filter, but left the pattern untouched, and firewall lines are now being parsed.
```
filter: "evt.Parsed.program == 'windows-firewall' and evt.Parsed.message contains ' DROP TCP ' and evt.Parsed.message contains ' RECEIVE'"
```
```
time="21-10-2022 07:48:43 PM" level=info msg="Acquisition Metrics:"
+---------------------------------------------------------------+------------+--------------+----------------+------------------------+
|                            SOURCE                             | LINES READ | LINES PARSED | LINES UNPARSED | LINES POURED TO BUCKET |
+---------------------------------------------------------------+------------+--------------+----------------+------------------------+
| file:C:\\Windows\\System32\\LogFiles\\Firewall\\pfirewall.log | 1.78k      | 65           | 1.72k          | 6                      |
+---------------------------------------------------------------+------------+--------------+----------------+------------------------+
```

**Comment by LaurenceJJones** [comment]
> In the file, **windows-firewall-logs.yaml,** I removed the space after RECEIVE in the filter, but left the pattern untouched, and firewall lines are now being parsed. 
> ```
> filter: "evt.Parsed.program == 'windows-firewall' and evt.Parsed.message contains ' DROP TCP ' and evt.Parsed.message contains ' RECEIVE'"
> ```
I need a reason to spin up another windows server so I will try this and see if it works.
