### ISSUE TITLE
crowdsecurity/apache2 distinguish access logs from error logs

### ISSUE THREAD

**Issue by ririsoft** [crowdsecurity/hub#51]
Hello,

`crowdsecurity/nginx` makes the distinction between access logs and error logs.
Could we have the same for apache2 logs, please ?
This is quiet straightforward:

Example of error logs:

```
[Sat Nov 14 18:38:54.891620 2020] [authz_core:error] [pid 30873:tid 140345882953472] [client 42.231.130.238:36326] AH01630: client denied by server configuration: /var/www/default/boaform
[Sat Nov 14 18:39:39.518161 2020] [authz_core:error] [pid 30873:tid 140347174807296] [client 95.38.202.202:59281] AH01630: client denied by server configuration: /var/www/default/
[Sat Nov 14 19:04:36.773086 2020] [auth_basic:error] [pid 30873:tid 140347272279808] [client 192.168.1.1:46510] AH01617: user toto: authentication failure for "/backup/": Password Mismatch
```

What do you think ?
Cheers.

**Comment by AlteredCoder** [comment]
Hello @ririsoft 

I'm closing this issue since this is needed to solve #50

**Comment by ririsoft** [comment]
I do not understand why this is closed ? #50 could benefit from this one for Apache logs, but for other kind of logs (such Nginx) #50 have nothing to do with this one. Also separating apache2 access logs from error logs could benefit to other scenarios than brute force.

**Comment by buixor** [comment]
Hello @ririsoft,

I think he closed this one because this is kinda implied by #50 
The apache2 error log parser is being created to solve #50, fixing this one at the same time.

Is it good for you ?

**Comment by ririsoft** [comment]
All good, thanks for the clarification.
