### ISSUE TITLE
How to remove port from ip-string in a parser?

### ISSUE THREAD

**Issue by timokoessler** [crowdsecurity/hub#518]
I am currently working on a parser & scenario for MongoDB. The problem is that MongoDB logs the IP address including the port. In the docs I didn't find any way to split a string. In addition, ipv6 addresses contain colons, so its only possible to remove everything after the last colon.
Is there a possibility that I have overlooked?
Thank you.

```json
{
   "t":{ "$date":"2022-07-28T18:16:40.466+02:00" },
   "s":"I",
   "c":"ACCESS",
   "id":20249,
   "ctx":"conn12",
   "msg":"Authentication failed",
   "attr":{
      "mechanism":"SCRAM-SHA-256",
      "speculative":true,
      "principalName":"root",
      "authenticationDatabase":"admin",
      "remote":"127.0.0.1:1053",
      "extraInfo": {
      },
      "error":"AuthenticationFailed: SCRAM authentication failed, storedKey mismatch"
   }
}
```

**Comment by AlteredCoder** [comment]
Hello,recu
Can you share with us how you retrieve the IP address in your parser please? If you use the JSON helpers, you might need to extract the IP and the PORT from it with a grok:

```
    - grok:
        pattern: '%{IPORHOST:remote_addr}:%{NUMBER}'
        expression: JsonExtract(evt.Line.Raw, "request.remote_addr")
```
for example.

For example we are doing this in https://github.com/crowdsecurity/hub/blob/master/parsers/s01-parse/crowdsecurity/caddy-logs.yaml#L22
