### ISSUE TITLE
Proxmox add multilingual support

### ISSUE THREAD

**Issue by OcelotNat** [crowdsecurity/hub#520]
Hello,

parser / s01-parse / fulljackz / proxmox-logs.yaml

the parser seeks error messages in english : 
`  PVE_AUTH_FAIL: 'authentication failure; rhost=%{IP:client_ip} user=%{USERNAME:source_user}@%{WORD:realm} msg=Authentication failure'`
or in french, the message is `msg=Échec de l’authentification`

It's work without the msg string : 
`PVE_AUTH_FAIL: 'authentication failure; rhost=%{IP:client_ip} user=%{USERNAME:source_user}@%{WORD:realm} msg='`

No problem with "no such user" which is not translated (at this time...) in french, but maybe for other languages ?

**Comment by a1ad** [comment]
@fulljackz why did you differentiate "Authentication failure" and "no such user"?

Can we change the pattern to a single one? Like @OcelotNat suggested? It is a quick fix.

**Comment by fulljackz** [comment]
Hi,

Hum if I try to remember (which is not an easy thing :smile: ), I would say that I decided to differentiate the two strings to apply a different analysis based on the behavior.

Probably that I did not want to ban directly an Authentification failure as quickly as a no such user, which is clearly a bruteforce attempt.

On the other hand, the behavior as describe above is not part of the decision. So yes, we can change it, I dont have problem with that as long as it helps my french colleagues :smile:

**Comment by fulljackz** [comment]
> @fulljackz why did you differentiate "Authentication failure" and "no such user"?
> 
> Can we change the pattern to a single one? Like @OcelotNat suggested? It is a quick fix.

Done, the merge request is ok, waiting for integration.

**Comment by a1ad** [comment]
@OcelotNat can you test it?

**Comment by OcelotNat** [comment]
It's working fine for me !
Thanks for the job.
