### ISSUE TITLE
Legitimate requests for HLS .ts segments triggers http-crawl-non_statics ban

### ISSUE THREAD

**Issue by c-markwell** [crowdsecurity/hub#533]
I host videos using HTTP Live Streaming (HLS) MPEG Transport Stream segments (with a .ts file extension) on a web server that I monitor with CrowdSec.  As each HLS segment (containing a few seconds of video) is a separate http request, this results in a large number of legitimate requests from users in a short period of time, triggering a http-crawl-non_statics ban.

Would it be possible to update CrowdSec to ignore these legitimate requests?  Maybe by adding .TS to the list of static file extensions in `/parsers/s02-enrich/crowdsecurity/http-logs.yaml`?

Thank you very much for your assistance and for all your work on CrowdSec!

**Comment by buixor** [comment]
yes, it sounds like a good idea, thanks for the suggestion :)

**Comment by LaurenceJJones** [comment]
Closing due to fix merged
