### ISSUE TITLE
Nextcloud: “Trusted domain error” scenario

### ISSUE THREAD

**Issue by kaputtzich** [crowdsecurity/hub#542]
Hi there,

wouldn’t it be useful to add the “Trusted domain error” pattern to the nextcloud-logs.yaml parser file?
Had many rogue IP blocks when filtered with fail2ban.

Attached snippet of nextcloud.log and fail2ban filter config
[nextcloud.log](https://github.com/crowdsecurity/hub/files/9485185/nextcloud.log)
[nextcloud_fail2ban.conf.txt](https://github.com/crowdsecurity/hub/files/9485186/nextcloud_fail2ban.conf.txt)

**Comment by a1ad** [comment]
@LaurenceJJones you can close this one.
