### ISSUE TITLE
[Crowdsec] - bouncer inclusion - Traefik plugin

### ISSUE THREAD

**Issue by mathieuHa** [crowdsecurity/hub#559]
Hello,

We would like to introduce a new plugin @maxlerebourg and I wrote during a Traefik hackathon.
We have been using Treafik for a while now as our ingress controller and we discovered few month ago Crowdsec.

We strongly believe on crowdsec and the sharing principale behind.

We have written a plugin direclty visible on Traefik plugin "hub" https://plugins.traefik.io/plugins.

This plugins allows connection to a Crowdsec container (the LAPI).

| Mode | Description |
|------|------|
| none | If the client IP is on ban list, it will get a http code 403 response. Otherwise, request will continue as usual. All request call the Crowdsec LAPI |
| live | If the client IP is on ban list, it will get a http code 403 response. Otherwise, request will continue as usual.    The bouncer can leverage use of a local cache in order to reduce the number of requests made to the Crowdsec LAPI. It will keep in cache the status for  each IP that makes queries. |
| stream | Streaming mode allows you to keep in the local cache only the Banned IPs, every requests that does not hit the cache is authorized. Every minute, the cache is updated with news from the Crowdsec LAPI. |

Source repository of your bouncer: https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/
Software licence used: [Apache](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/blob/main/LICENSE)
Current status of the bouncer (stage: dev/unstable/stable) stable 
Documentation (can be simply in the README.md): https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/blob/main/README.md
Link to existing tests if applicable (either functional or unit tests): tests is planned to be taken care in a next release

We are currently working on it to clean the codebase, stabilize it, and are using it in preproduction environnement for our company [Primadviz](Primadviz.com).

We'll be happy to discuss with you about his integration on Crowdsec hub.

**Comment by mathieuHa** [comment]
I've just updated the previous comment removing the standalone mode following Crowdsec advice.

We just released a [new version](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/releases/tag/v1.1.0) of the plugin/Bouncer including some performance improvement (shared cache between all instances of the bouncer).

Can you tell us if our bouncer now meets the requirements and if we can get it referenced in the Crowdsec hub ?

Thanks :)

**Comment by LaurenceJJones** [comment]
Hey!

Let me start by saying Thank you! it's great to see another potential bouncer be added to our list. We do already have a traefik bouncer, however, variety is the spice of life and offering choices to user is key. We may need to do a deep dive the differences between the traefik options to make it clear what the difference is. (If any!)

I do note something straight away I noticed you a not setting a custom UA (We used this so when a user run `cscli bouncers list` they can easily note (without looking at key name) what bouncer is format normally is `crowdsec/<type>-<version>`)

I will bring this up with the team tomorrow, and let know if any changes are required!

**Comment by LaurenceJJones** [comment]
We included your bouncer into the hub, Once it has updated properly there should be a link and we periodically update the readme with the latest from your repo.

**Comment by mathieuHa** [comment]
Hi @LaurenceJJones,

Thank you.
However i'm wondering if anything is missing, our bouncer is not up on the HUB yet.

I've seen your commit https://github.com/crowdsecurity/hub/commit/eb92852dde6d98a666df1543b73f54838275bfad that added it in the file https://raw.githubusercontent.com/crowdsecurity/hub/master/blockers/list.json

But I'm wondering if it's not the following file that is fetched from Crowdsec Hub https://github.com/crowdsecurity/hub/blob/master/blockers.json served by https://hub-cdn.crowdsec.net/master/blockers.json
In this file our bouncer is not present.

Do we have to do something else on our side to make it work ?
Thank you

**Comment by LaurenceJJones** [comment]
Its purely our side. The way the blocker list is generated we are getting rate limited. We are investigating and working on fix.
