### ISSUE TITLE
ssh logs are not parsed

### ISSUE THREAD

**Issue by andyoulovexy** [crowdsecurity/hub#584]
![image](https://user-images.githubusercontent.com/38940994/198949295-1eff8fd0-36bb-472d-ba83-b7bf99653a6b.png)

**Comment by LaurenceJJones** [comment]
Could you try the type `syslog` instead of `sshd`

**Comment by andyoulovexy** [comment]
> 



> Could you try the type instead of . Pasting the lines in the issue can also help us instead of an image, wrap them around ````syslog``sshd`

Oct 31 15:33:23 localhost unix_chkpwd[2681]: password check failed for user (wax)
Oct 31 15:33:23 localhost sshd[2679]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=test.xxx.com  user=wax
Oct 31 15:33:25 localhost sshd[2679]: Failed password for wax from 10.9.9.73 port 49836 ssh2
Oct 31 15:33:27 localhost unix_chkpwd[2682]: password check failed for user (wax)
Oct 31 15:33:29 localhost sshd[2679]: Failed password for wax from 10.9.9.73 port 49836 ssh2
Oct 31 15:33:31 localhost unix_chkpwd[2683]: password check failed for user (wax)
Oct 31 15:33:33 localhost sshd[2679]: Failed password for wax from 10.9.9.73 port 49836 ssh2
Oct 31 15:33:33 localhost sshd[2679]: Connection closed by 10.9.9.73 port 49836 [preauth]
Oct 31 15:33:33 localhost sshd[2679]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=test.xxx.com  user=wax
Oct 31 15:33:35 localhost unix_chkpwd[2686]: password check failed for user (wax)
Oct 31 15:33:35 localhost sshd[2684]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=test.xxx.com  user=wax
Oct 31 15:33:37 localhost sshd[2684]: Failed password for wax from 10.9.9.73 port 49966 ssh2
Oct 31 15:33:38 localhost unix_chkpwd[2687]: password check failed for user (wax)
Oct 31 15:33:40 localhost sshd[2684]: Failed password for wax from 10.9.9.73 port 49966 ssh2
Oct 31 15:33:42 localhost unix_chkpwd[2688]: password check failed for user (wax)
Oct 31 15:33:44 localhost sshd[2684]: Failed password for wax from 10.9.9.73 port 49966 ssh2
Oct 31 15:33:44 localhost sshd[2684]: Connection closed by 10.9.9.73 port 49966 [preauth]
Oct 31 15:33:44 localhost sshd[2684]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=test.xxx.com  user=wax
Oct 31 15:33:47 localhost unix_chkpwd[2691]: password check failed for user (wax)
Oct 31 15:33:47 localhost sshd[2689]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=test.xxx.com  user=wax

**Comment by LaurenceJJones** [comment]
The line is working if you have white list installed (By default) private ip ranges are ignored unless you adapt or remove the collection
```
line: Oct 31 15:33:29 localhost sshd[2679]: Failed password for wax from 10.9.9.73 port 49836 ssh2
	├ s00-raw
	|	└ 🟢 crowdsecurity/syslog-logs (first_parser)
	├ s01-parse
	|	├ 🔴 crowdsecurity/apache2-logs
	|	└ 🟢 crowdsecurity/sshd-logs (+9 ~1)
	├ s02-enrich
	|	├ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	|	├ 🟢 crowdsecurity/geoip-enrich (+9)
	|	├ 🔴 crowdsecurity/http-logs
	|	└ 🟢 crowdsecurity/whitelists (~2 [whitelisted])
	└-------- parser failure 🔴
```
Either edit:
`/etc/crowdsec/parsers/s02-encrich/whitelist.yaml`
Or
`cscli parsers remove crowdsecurity/whitelist`

**Comment by andyoulovexy** [comment]
> 

thanks,let me try.

**Comment by andyoulovexy** [comment]
> cscli parsers remove crowdsecurity/whitelists &&sudo systemctl reload crowdsec .it's work

"/etc/crowdsec/parsers/s02-enrich/whitelists.yaml" remove private string can't work

**Comment by LaurenceJJones** [comment]
Please could you elaborate? `remove private string can't work` ?

**Comment by andyoulovexy** [comment]
> Please could you elaborate? `remove private string can't work` ?
Now it's work.thanks

**Comment by LaurenceJJones** [comment]
Closing due to confirmation it working
