### ISSUE TITLE
unable to load hubtest (on Ubuntu server 20.04)

### ISSUE THREAD

**Issue by harmlessdrudge** [crowdsecurity/hub#598]
```
ubuntu@ubuntu:~$ sudo cscli hub update
INFO[22-11-2022 08:24:10 PM] hub index is up to date                      
INFO[22-11-2022 08:24:10 PM] Wrote new 511426 bytes index to /etc/crowdsec/hub/.index.json 
ubuntu@ubuntu:~$ sudo cscli hubtest list
FATA[22-11-2022 08:25:37 PM] unable to load hubtest: unable to read index file: open /home/ubuntu/.index.json: no such file or directory 
```

?

**Comment by LaurenceJJones** [comment]
What are you trying to achieve? That command should be run when you are testing / generating parsers? if you are trying to update or list hub items try
```
sudo cscli hub --help
```

**Comment by harmlessdrudge** [comment]
What I was trying to achieve was to find out what the purpose of the command 

`sudo cscli hubtest list`

was, having seen that other parameters all took an argument

```
ubuntu@ubuntu:~$ sudo cscli hubtest
Run functional tests on hub configurations (parsers, scenarios, collections...)


Usage:

  cscli hubtest [command]

Available Commands
  clean        clean [test_name]
  coverage     coverage
  create       create [test_name]
  eval         eval [test_name]
  explain      explain [test_name]
  info         info [test_name]
  list         list
  run          run [test_name]
```

Shouldn't the output of the command should be something like

list       [ parsers | collections | scenarios ] list

(or even the other way around--for verb then object consistency) ?

**Comment by LaurenceJJones** [comment]
I understand, however, this is testing tools. If a user wanted this information they can
```
cscli parsers list
cscli scenarios list
cscli collections list
```

They no need for us to expand this command further since it purely testing.
