### ISSUE TITLE
support for MariaDB logs

### ISSUE THREAD

**Issue by suixhxy** [crowdsecurity/hub#602]
### What would you like to be added?

Hi,
please add support for MariaDB logs instead of mysql.log only.

The database version I'm using is  mariadb5.5.56

1、
The log path is：
/var/log/mariadb/mariadb.log

The log output format is：
221128 14:48:56 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:48:59 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:02 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:05 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:07 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:15 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:17 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
2、
I know it supports this style：
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
2021-11-09  5:13:11 8 [Warning] Access denied for user 'example-user'@'192.168.1.192' (using password: YES)
3、
But I want it to support this style：
221128 14:48:56 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:48:59 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:02 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:05 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:07 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:15 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221128 14:49:17 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)

### Why is this needed?

Because I need to be able to support this format：
221126 14:50:54 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221126 14:50:57 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)

**Comment by suixhxy** [comment]
Default log format of the mariadb5.5.56 database is：


221129  8:35:26 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221129  8:35:27 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221129  8:35:29 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)
221129  8:35:31 [Warning] Access denied for user 'root'@'192.168.1.192' (using password: YES)


I cannot change the log format of the database。How do I match it to the mariadb-logs.yaml file?

**Comment by LaurenceJJones** [comment]
I will work on this. However, for starters you need to make sure you are latest version of Crowdsec as any version before will not have custom time/date formatter.

**Comment by suixhxy** [comment]
Thank you. Thank you very much
I'll download a new version and try it out

**Comment by suixhxy** [comment]
Thank you. Thank you very much。
1、my linux is  centos7.8 。
2、The way I installed it before  ：
curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh | sudo bash
yum install crowdsec -y
yum install crowdsec-firewall-bouncer-iptables  -y
cscli collections install crowdsecurity/mariadb


3、How do I upgrade it to the latest version?






---- Replied Message ----
| From | Laurence ***@***.***> |
| Date | 11/30/2022 17:59 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [crowdsecurity/hub] support for MariaDB logs (Issue #602) |

I will work on this. However, for starters you need to make sure you are latest version of Crowdsec as any version before will not have custom time/date formatter.

**Comment by suixhxy** [comment]
Thank you. Thank you very much。
1、my linux is  centos7.8 。
2、The way I installed it before  ：
curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh | sudo bash
yum install crowdsec -y
yum install crowdsec-firewall-bouncer-iptables  -y
cscli collections install crowdsecurity/mariadb

3、How do I upgrade it to the latest version?
4、I was hoping you could help me，Thank you.

**Comment by LaurenceJJones** [comment]
Since my changes are not merged they are not available through the normal `cscli install` command. You would need to run something like
```
curl -s https://raw.githubusercontent.com/crowdsecurity/hub/645cc089cd8708be94a64db8b4c1a6002e33fd35/parsers/s01-parse/crowdsecurity/mariadb-logs.yaml > /etc/crowdsec/hub/parsers/s01-parse/crowdsecurity/mariadb-logs.yaml

sudo systemctl reload crowdsec.service
```

**Comment by suixhxy** [comment]
Thank you. Thank you very much，
After my tests, it worked
thanks again ！


---- Replied Message ----
| From | Laurence ***@***.***> |
| Date | 12/1/2022 16:38 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [crowdsecurity/hub] support for MariaDB logs (Issue #602) |

Since my changes are not merged they are not available through the normal cscli install command. You would need to run something like

curl -s https://raw.githubusercontent.com/crowdsecurity/hub/645cc089cd8708be94a64db8b4c1a6002e33fd35/parsers/s01-parse/crowdsecurity/mariadb-logs.yaml > /etc/crowdsec/hub/parsers/s01-parse/crowdsecurity/mariadb-logs.yaml

sudo systemctl reload crowdsec.service

**Comment by suixhxy** [comment]
Thank you. Thank you very much，
After my tests, it worked
thanks again ！
