### ISSUE TITLE
Suricata EVE Json Parser doesn't work in North America

### ISSUE THREAD

**Issue by juched78** [crowdsecurity/hub#607]
In my research using the cscli explain command I realized that Crowdsec would not parse my Suricata EVE Json based logs. Looking at the parser I see that the grok command looks for a + sign in the timestamp, meaning only UTC+ timezones (ie.. Europe through Asia) would work.

I replaced this line:
pattern: '%{SURICATA_EVE_TS:time}\+%{INT}'

with:
pattern: '%{SURICATA_EVE_TS:time}\-%{INT}'

and now is parses..  I am UTC-5 in the Eastern Timezone.

Should be able to create a pattern which works with both + and - timezones so it works everywhere.

Thank you!

**Comment by LaurenceJJones** [comment]
Great catch, we are all utc+. Easy fix should be but I will test and implement a test for + timestamps so we make sure not to break in future
```
pattern: '%{SURICATA_EVE_TS:time}(\-|\+)%{INT}'
```
