### ISSUE TITLE
Listing collections, configurations and bouncers relies on GitHub API which has a rate limit

### ISSUE THREAD

**Issue by C-Duv** [crowdsecurity/hub#621]
I want to have a look at all available bouncers (and maybe collections and configurations) on the [Hub](https://hub.crowdsec.net) but the list stays empty (home page says "0 Collections & 0 Configurations & 0 Bouncers", and lists keeps displaying "Loading items...").

The webpage performs an HTTP call to `https://api.github.com/repos/crowdsecurity/hub/branches?per_page=100` which, in my case, gets a 403 HTTP response with the following error:

```JSON
{
    "message":"API rate limit exceeded for {MY_IP_ADDRESS}. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

So I guess the Hub is asking the client/browser to perform requests to the GitHub API (instead of performing those server-side).

Could it be avoided? Or at least to be able to display some basic informations (names, purpose and homepage URLs) without the API?

**Comment by LaurenceJJones** [comment]
Thank you for bringing this forward. This is known to us, however, we do have a cloudfront that delivers this to the crowdsec agents (cscli hub <action>).

**Comment by LaurenceJJones** [comment]
Hey, we have improved this. However we cannot 100% remove the github api for user images.

So we have create a fallback if you are rate limited you will still see the information but no user profiles / old versions of crowdsec.

We have found a potential issue which lead to an unnecessary extra github requests. This has also been resolved. Closing for now.

**Comment by C-Duv** [comment]
I can confirm it worked great today: I opened 10 pages of the Hub without being rate-limited 👍
