### ISSUE TITLE
dovecot-logs.yaml: HaProxy -> Dovecot via ProxyProtocol: IPv4 address not parsed correctly 

### ISSUE THREAD

**Issue by paulastronaut** [crowdsecurity/hub#634]
As described in [https://discourse.crowdsec.net/t/haproxy-dovecot-via-proxyprotocol-ipv4-address-not-parsed-correctly/1103](url), IPv4 addresses in my setup are not parsed correctly.

Setup: I have HAProxy set up as a reverse proxy. HAProxy forwards IMAP ports to Dovecot via [ProxyProtocol](https://www.haproxy.com/de/blog/haproxy/proxy-protocol/), so that the original IP address is transmitted to Dovecot (and not the IP address of the server proxy is running on). All relevant systems run on Debian Bookworm. Crowdsec is running in version 1.4.3 I don’t know if this is related to the behavior.

Observed behavior: When an login attempt from an IPv4 address fails, Dovecot logs the following message:

`    Jan 13 14:53:45 imap-login: Info: Disconnected (auth failed, 2 attempts in 4 secs): user=[xxx@xxx.xx](mailto:xxx@xxx.xx), method=PLAIN, rip=::ffff:xxx.xxx.xxx.xxx, lip=::ffff:xxx.xxx.xxx.xxx, TLS, session=`

Via `cscli explain`, I found out that the parser wrongly detects the IP address

`create evt.Meta.source_ip : ::ffff:xxx.xxx.xxx.xxx`

which then subsequently gets banned, with no effect, presumably because `::ffff:xxx.xxx.xxx.xxx` isn’t a valid IPv4 address.

Expected behavior is that the correct IPv4 address is parsed.

Solution: I could solve this issue in my case by adding the RegEx `??(::ffff:)` into dovecot-logs.yaml at the correct location:

`      pattern: "%{WORD:protocol}-login: %{DATA:dovecot_login_message}: user=<%{DATA:dovecot_user}>.*, rip=??(::ffff:)%{IP:dovecot_remote_ip}, lip=%{IP:dovecot_local_ip}"`

No idea if this is the correct way to solve this or if it breaks other usecases. If correct, the RegEx should probably be added to the lip-Part as well.

**Comment by paulastronaut** [comment]
I discovered that my approach described above breaks IPv6 detection. I think this is a better way:

`      pattern: "%{WORD:protocol}-login: %{DATA:dovecot_login_message}: user=<%{DATA:dovecot_user}>.*, rip=(::ffff:)?%{IP:dovecot_remote_ip}, lip=(::ffff:)?%{IP:dovecot_local_ip}"`

**Comment by LaurenceJJones** [comment]
> I discovered that my approach described above breaks IPv6 detection. I think this is a better way (with adding the RegEx to the lip part as well):
> 
> ` pattern: "%{WORD:protocol}-login: %{DATA:dovecot_login_message}: user=<%{DATA:dovecot_user}>.*, rip=(::ffff:)?%{IP:dovecot_remote_ip}, lip=(::ffff:)?%{IP:dovecot_local_ip}"`

This would of been my recommendation, I'm guessing the haproxy whilst proxying the IP is adding the prefix to the remote ip?

**Comment by paulastronaut** [comment]
Yeah, I found out that [HAProxy adds the string to IPv4 addresses in certain configurations](https://cbonte.github.io/haproxy-dconv/2.5/configuration.html#7.1.6). With the changes described [here](https://discourse.haproxy.org/t/make-haproxy-stop-prepending-to-ipv4-addresses-in-x-forwarded-for/3368), the IPv4 address is forwarded in its usual form, without the prefix. So a change in CrowdSec is not necessary at all cost.

However, I think that the additional RegEx would make CrowdSec more robust for configurations like mine. I am not sure how much computational cost the additional RegEx brings into the equation. I leave it up to the devs if this is something that should be added to CrowdSec.

**Comment by LaurenceJJones** [comment]
Going to close as not planned but will keep this reference as any service proxied will have same cause and effect
