### ISSUE TITLE
mariadb-logs: MariaDB logs not parsed because of a missing letter

### ISSUE THREAD

**Issue by paulastronaut** [crowdsecurity/hub#639]
In my Debian Bullseye setup of MariaDB (standard packages) with CrowdSec 1.4.3, MariaDB logs are not parsed. The log lines enter the syslog parser, but never get picked up by mariadb-logs. I found out that this is due to a missing letter.

The MariaDB log file entry for a login attempt with a wrong password looks like this:

`Jan 14 09:21:50 data mariadbd[609]: 2023-01-14  9:21:50 15647 [Warning] Access denied for user 'xxx'@'2001:db8::0001' (using password: YES)`

The message comes from mariadb**d**, the daemon. However, mariadb-logs filters for

`filter: "evt.Parsed.program == 'mariadb'"`

without d. Took me some time to find that error... Changing the filter criterium to 'mariadbd' solves the issue.

I am not sure if this is debian specific or not. If it isn't, it's a simple bug. If it is, I assume this hits most Debian/MariaDB users, and I think it would be worth while adding a second filter criterium 'mariadbd'.

**Comment by LaurenceJJones** [comment]
We can change the `evt.Parsed.program startsWtih 'mariadb'` so it will always cover it for both

**Comment by paulastronaut** [comment]
Sounds reasonable, thanks.

Talking about little details: You probably meant `startsWith`, not `startsWtih`. Just in case you want to copy&paste... :-)

**Comment by LaurenceJJones** [comment]
That's what I get for typing too fast! thank you, I can see about pushing a fix sometime today.
