### ISSUE TITLE
[Feature Request] Scenario for crowdsec's ban logs and permanent ban

### ISSUE THREAD

**Issue by casesolved-co-uk** [crowdsecurity/hub#646]
If you intend to be a credible alternative to fail2ban, this is essential. You need:

- An optional collection/scenario that parses crowdsec’s own logs
- Default rule, for example: 3 ban log entries leads to longer ban
- A permanent ban capability 

(Be careful of ban loops)

Look up fail2ban’s recidive jail
https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/recidive.conf
https://github.com/fail2ban/fail2ban/blob/f93a538693f25c5e735cf88a0f2fc942b943d18b/config/jail.conf#L822
https://discourse.crowdsec.net/t/how-to-make-permament-ban/823

**Comment by LaurenceJJones** [comment]
Hey thank you for your feedback, we have thought about the permanent remediation beforehand, however, since we have multiple bouncers we don't know if users would get confused if an IP is being handled in a certain way. This has to be explorer.

- Default rule, for example: 3 ban log entries leads to longer ban
This is already configurable for the user via the https://docs.crowdsec.net/docs/next/profiles/format#duration_expr

- An optional collection/scenario that parses crowdsec’s own logs
Our API logs are in nginx format so we can use the current nginx format and scenario out of the box

**Comment by casesolved-co-uk** [comment]
> since we have multiple bouncers we don't know if users would get confused if an IP is being handled in a certain way. This has to be explored.

There's nothing that need to be explored. recidive has been an option in fail2ban for years. If there are any concerns, just make it optional. But frankly if an IP is a persistent offender it deserves to be banned.

**Comment by LaurenceJJones** [comment]
> > since we have multiple bouncers we don't know if users would get confused if an IP is being handled in a certain way. This has to be explored.
> 
> There's nothing that need to be explored. recidive has been an option in fail2ban for years. If there are any concerns, just make it optional. But frankly if an IP is a persistent offender it deserves to be banned.

Well yes we need to explore how we can handle it within our agent, as there are multiple configurations we need to ensure we go down the best path. I do agree with you a  persistent offender it deserves to be banned.

**Comment by casesolved-co-uk** [comment]
>   This is already configurable for the user via the https://docs.crowdsec.net/docs/next/profiles/format#duration_expr

Interesting, is there any documentation on how to set up a blanket custom rule so that every ban from the same IP gets exponentially longer?

**Comment by LaurenceJJones** [comment]
> > This is already configurable for the user via the https://docs.crowdsec.net/docs/next/profiles/format#duration_expr
> 
> Interesting, is there any documentation on how to set up a blanket custom rule so that every ban from the same IP gets exponentially longer?

Yes, within `/etc/crowdsec/profiles.yaml` if you installed lately you can uncomment to `duration_expr` that is in the default profile. By default it will have an increasing ban timer of 4 hours.

**Comment by casesolved-co-uk** [comment]
> > > This is already configurable for the user via the https://docs.crowdsec.net/docs/next/profiles/format#duration_expr
> > 
> > 
> > Interesting, is there any documentation on how to set up a blanket custom rule so that every ban from the same IP gets exponentially longer?
> 
> Yes, within `/etc/crowdsec/profiles.yaml` if you installed lately you can uncomment to `duration_expr` that is in the default profile. By default it will have an increasing ban timer of 4 hours.

Right, So I could do something like:

```
duration_expr: Sprintf('%dh', Pow(GetDecisionsCount(Alert.GetValue()) + 1, 2) * 4)
```
or, more aggressive:
```
duration_expr: Sprintf('%dh', Pow(4, GetDecisionsCount(Alert.GetValue()) ) )
```

https://github.com/crowdsecurity/crowdsec/blob/master/config/profiles.yaml

**Comment by LaurenceJJones** [comment]
Yes but I believe the Pow function provide by EXPR turns into a float which has some issues with Sprintf check https://discourse.crowdsec.net/t/duration-expr-and-exponentiation/988

**Comment by casesolved-co-uk** [comment]
> Yes but I believe the Pow function provide by EXPR turns into a float which has some issues with Sprintf check https://discourse.crowdsec.net/t/duration-expr-and-exponentiation/988
> 
> In short try: `%vh` or `%fh` as it will return a float and `%d` in Sprintf expects a int

What does the 'm' do in the 'dm' example, the [docs](https://pkg.go.dev/fmt#hdr-Printing) don't seem to say?

**Comment by casesolved-co-uk** [comment]
My examples aren't possible because the math module and Pow function aren't available in the expression

**Comment by casesolved-co-uk** [comment]
Closing because similar functionality exists
