### ISSUE TITLE
False positive http-crawl-non_statics with Nextcloud Mail App

### ISSUE THREAD

**Issue by cuthulino** [crowdsecurity/hub#683]
(similar to #669)

Using the Nextcloud Mail App bans me with http-crawl-non_statics.
Looks like sth. like `mail/api` should be added to the whitelist?

Here is the Output of `cscli alerts inspect`:

Loz: edit edt edit.

**Comment by cuthulino** [comment]
Thanks for your attention. 
I checked them before and these are only public accessible addresses like UPS delivery, some info addresses of shops etc.
Nothing private leaked here.

**Comment by LaurenceJJones** [comment]
I will find time today to push an update for you and other linked issue
