### ISSUE TITLE
Improvement/services: target caddy and haproxy logs

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/hub#69]
Describe the solution you'd like

It would be nice to be able to have crowdsec recognize haproxy or caddy reverse proxies as services that have been installed.
I think it would complement both tools if crowdsec could parse their log files and be able to apply e.g. the netfilter/iptables bouncer when malicious activity is detected.

**Comment by vumdao** [comment]
Anyone can please help support for haproxy logs.

**Comment by buixor** [comment]
Hello @vumdao ,

Would you have some logs to share for haproxy ? It would greatly help fast forwarding the process :slightly_smiling_face:

**Comment by vumdao** [comment]
@buixor  HAProxy logs
```
Mar 12 06:56:29 ec2-proxy haproxy[23481]: 22.118.26.10:10285 [12/Mar/2021:06:56:28.088] fe-verify~ maskurl/dns 0/0/0/1263/1264 200 20602 - - ---- 19/19/3/4/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:29 ec2-proxy haproxy[23481]: 22.118.26.10:21264 [12/Mar/2021:06:56:28.961] fe-verify~ maskurl/dns 0/0/1/783/784 200 15211 - - ---- 17/17/3/4/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:29 ec2-proxy haproxy[23481]: 22.118.26.10:9303 [12/Mar/2021:06:56:29.604] fe-verify~ maskurl/dns 0/0/1/243/245 200 14553 - - ---- 16/16/2/3/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:29 ec2-proxy haproxy[23481]: 22.118.26.10:15775 [12/Mar/2021:06:56:29.267] fe-verify~ maskurl/dns 0/0/1/704/705 200 14140 - - ---- 15/15/1/2/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:30 ec2-proxy haproxy[23481]: 22.118.26.10:53289 [12/Mar/2021:06:56:28.735] fe-verify~ maskurl/dns 0/0/1/1327/1329 200 23107 - - ---- 14/14/0/1/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:30 ec2-proxy haproxy[23481]: 52.74.226.20:41006 [12/Mar/2021:06:56:30.126] fe-verify~ maskurl/dns 0/0/0/316/317 200 16384 - - ---- 14/14/0/1/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:31 ec2-proxy haproxy[23481]: 54.36.149.12:57868 [12/Mar/2021:06:56:31.089] fe-verify~ maskurl/dns 0/0/1/242/243 200 10054 - - ---- 14/14/0/1/0 0/0 "POST /job/11111/non-it-it HTTP/1.1"
Mar 12 06:56:34 ec2-proxy haproxy[23481]: 22.118.26.10:40391 [12/Mar/2021:06:56:34.564] fe-verify~ maskurl/dns 0/0/0/253/253 200 15216 - - ---- 14/14/0/1/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:35 ec2-proxy haproxy[23481]: 22.118.26.10:56818 [12/Mar/2021:06:56:34.830] fe-verify~ maskurl/dns 0/0/1/262/264 200 14553 - - ---- 15/15/1/2/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:35 ec2-proxy haproxy[23481]: 22.118.26.10:16242 [12/Mar/2021:06:56:34.864] fe-verify~ maskurl/dns 0/0/1/723/725 200 21008 - - ---- 14/14/1/2/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:35 ec2-proxy haproxy[23481]: 22.118.26.10:30067 [12/Mar/2021:06:56:35.324] fe-verify~ maskurl/dns 0/0/1/401/403 200 23105 - - ---- 13/13/0/1/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:37 ec2-proxy haproxy[23481]: 22.118.26.10:14223 [12/Mar/2021:06:56:36.810] fe-verify~ maskurl/dns 0/0/1/319/321 200 14557 - - ---- 13/13/0/1/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:37 ec2-proxy haproxy[23481]: 22.118.26.10:58461 [12/Mar/2021:06:56:37.140] fe-verify~ maskurl/dns 0/0/1/146/148 200 15207 - - ---- 13/13/0/1/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:37 ec2-proxy haproxy[23481]: 22.118.26.10:60924 [12/Mar/2021:06:56:37.567] fe-verify~ maskurl/dns 0/0/1/163/165 200 14562 - - ---- 14/14/2/3/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:37 ec2-proxy haproxy[23481]: 22.118.26.10:6460 [12/Mar/2021:06:56:37.441] fe-verify~ maskurl/dns 0/0/1/482/484 200 20605 - - ---- 13/13/1/2/0 0/0 "GET / HTTP/1.1"
Mar 12 06:56:38 ec2-proxy haproxy[23481]: 22.118.26.10:12599 [12/Mar/2021:06:56:37.690] fe-verify~ maskurl/dns 0/0/1/414/416 200 23104 - - ---- 12/12/1/2/0 0/0 "GET / HTTP/1.1"
```

**Comment by buixor** [comment]
Hello @vumdao !

I started to work on haproxy logs and have a possibly working one : https://github.com/crowdsecurity/hub/pull/187

You can try it by using `cscli hub update --branch haproxy_collection` and `cscli collections install crowdsecurity/haproxy --branch haproxy_collection`.

A few questions tho :
 - From the logs you pasted, the default log format doesn't have a user agent, is it correct ?
 - Would you happen have (we can exchange privately if you prefer) logs that represent some classical attacks so I can ensure that haproxy logs parser will work well with existing scenarios ?

Let me know,

**Comment by vumdao** [comment]
@buixor 
For more information, my HA-Proxy version 2.0.13-2ubuntu0.1 2020/09/08

> * From the logs you pasted, the default log format doesn't have a user agent, is it correct ?
I run the haproxy under systemD service so I have no idea about `user agent`

> * Would you happen have (we can exchange privately if you prefer) logs that represent some classical attacks so I can ensure that haproxy logs parser will work well with existing scenarios ?
I would prefer sending you the log privately

**Comment by buixor** [comment]
@vumdao if you have logs, you can contact us privately via https://doc.crowdsec.net/contributing/#contacting-the-team :+1:

**Comment by buixor** [comment]
https://hub.crowdsec.net/author/crowdsecurity/configurations/haproxy-logs and https://hub.crowdsec.net/author/crowdsecurity/configurations/caddy-logs both exists !
