### ISSUE TITLE
Add support for passbolt

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/hub#699]
https://www.passbolt.com/

Finally, a password manager built for organizations that take their security and privacy seriously. Passbolt is trusted by 15 000 of them worldwide, including F500 companies, the defense industry, universities, startups and many others.

I havent tested it yet but I believe we could detect alot of bruteforcing.

**Comment by LePresidente** [comment]
Had a brief look at this, so looks like all the authentication is done client side in the addon, the server logs never show any authentication logs that i can see.

**Comment by LaurenceJJones** [comment]
Thank you for checking. I'll close for now.
