### ISSUE TITLE
ssh scenario should  ban 'no matching host key type found'  and  'no matching key exchange method found'

### ISSUE THREAD

**Issue by LePresidente** [crowdsecurity/hub#756]
My one server is being spammed by the following, these should probably be detected in a scenario  as a ssh bruteforce even if it doesn't even try login.

`
Jun  8 10:44:36 <redacated> sshd[3204729]: Unable to negotiate with 123.57.135.134 port 45626: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]
Jun  7 04:07:10 <redacated> sshd[1941162]: Unable to negotiate with 206.189.59.169 port 34386: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]
`

I can probably create a PR for this in a day or two

**Comment by blotus** [comment]
Hello,

This log can be emitted in legitimate cases (eg, you upgraded your workstation to a recent SSH, and you have an older SSH on your server/router/....), I fear it might lead to lots of false positives.

I'm not a fan of adding this to a "default" collection, but I don't really have any issues with this if you add it in a specific collection and scenario under your name (you can keep your changes in the parser, as crowdsec will stop processing the stage if the SSH parser returns successfully, so having 2 parsers interested in SSH logs likely won't behave as expected).

**Comment by LePresidente** [comment]
Hi,

Yea guess that makes sense, I'll update my pr to be a unique scenario instead of in the default

**Comment by LePresidente** [comment]
Ok PR has been updated moved to custom scenario
