### ISSUE TITLE
sshd-logs parser missing MAC in ssh_bad_keyexchange

### ISSUE THREAD

**Issue by hcsaustrup** [crowdsecurity/hub#775]
`SSHD_BAD_KEY_NEGOTIATION` needs `MAC` as well. Input example:

```
Jul  7 06:11:48 node1 sshd[1625360]: Unable to negotiate with 123.123.123.123 port 45296: no matching MAC found. Their offer: hmac-sha2-256,hmac-sha1,hmac-sha1-96 [preauth]
```

**Comment by LaurenceJJones** [comment]
Just to understand, cause I only use key exchange. This happens when you use have a MAC address whitelist or is there another MAC I dont know 😆

**Comment by hcsaustrup** [comment]
I'm assuming the error shows up when the client doesn't present any (H?)MACs supported by the server. I recently introduced a rather limited list, which is why many brute force attempts get this error before the more well-known ones.

I've currently got this very limited list in `/etc/ssh/sshd_config.d/tweaks.conf`:

```
MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
```

The OpenSSH client takes `-o MACs=...` but I didn't have any luck picking a MAC that wasn't supported by the server. I guess you'll either have to pick an obscure MAC on the server side or find an ancient client to test with to produce this log output.

**Comment by LePresidente** [comment]
Ok this has been added.

If you want crowdsec to ban these requests you will need to use my scenario though, its not in the standard collection.

https://hub.crowdsec.net/author/LePresidente/configurations/ssh-bad-keyexchange-bf
