### ISSUE TITLE
overseerr

### ISSUE THREAD

**Issue by sahara101** [crowdsecurity/hub#814]
Hi all :)

I noticed we have collections for jelyseerr and oombi, would it be possible to add one for overseer? 
Would Plex also be possible?

Thanks!

**Comment by LaurenceJJones** [comment]
Yes, if you can provide log samples and what you want to detect we can see about supporting it

**Comment by sahara101** [comment]
I asked what could be checked on the overseerr discord, as I am not sure.

**Comment by LePresidente** [comment]
i'll have a look at this shortly, since i just moved from jellyseerr to overseerr

**Comment by andreasbrett** [comment]
Overseerr will produce the following log output in `overseerr.log`. Unfortunately when run in a Docker container the logged IP is from the Docker network subnet.

```
2023-12-10T15:17:39.030Z [warn][API]: Failed sign-in attempt using invalid Overseerr password {"ip":"::ffff:10.9.100.9","email":"someone@nonexisting.com"}
```

Plex is authenticating agains app.plex.tv so you won't see the logs. Then again I'd assume the Plex cloud infra to have a stronger security posture than our home labs.
