### ISSUE TITLE
ProFTPd logfile will not parsed

### ISSUE THREAD

**Issue by dwydler** [crowdsecurity/hub#823]
Hi there,
today i setup Crowdsec for my ProFTPd instance. But i didn't get it to work. :-(
Everytime all entries of the logfile are marked as Unparsed. What am I doing wrong?

```
cscli metrics

Acquisition Metrics:
+-------------------------------------------------+------------+--------------+----------------+------------------------+
|                     Source                      | Lines read | Lines parsed | Lines unparsed | Lines poured to bucket |
+-------------------------------------------------+------------+--------------+----------------+------------------------+
| file:/var/log/proftpd/proftpd.log               | 1          | -            | 1              | -                      |
+-------------------------------------------------+------------+--------------+----------------+------------------------+

```

```
cscli collections list

COLLECTIONS
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Name                                  📦 Status   Version   Local Path
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────l
 crowdsecurity/proftpd                 ✔️ enabled   0.1       /etc/crowdsec/collections/proftpd.yaml

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
```
cscli parsers inspect crowdsecurity/proftpd
FATA[05-09-2023 19:13:45] unable to retrieve item.
```
```
cscli parsers inspect crowdsecurity/proftpd-logs
type: parsers
stage: s01-parse
name: crowdsecurity/proftpd-logs
filename: proftpd-logs.yaml
description: Parse proftpd logs
author: crowdsecurity
belongs_to_collections:
- crowdsecurity/proftpd
remote_path: parsers/s01-parse/crowdsecurity/proftpd-logs.yaml
version: "0.2"
local_path: /etc/crowdsec/parsers/s01-parse/proftpd-logs.yaml
localversion: "0.2"
localhash: 9921d4752e7337533472031d1495f9c4e4f870a558ea48f303e95e96a31f7f13
installed: true
downloaded: true
uptodate: true
tainted: false
local: false
```
```
cscli parsers inspect crowdsecurity/proftpd-bf
FATA[05-09-2023 19:15:13] unable to retrieve item.
```
```
cscli parsers inspect crowdsecurity/proftpd-bf_user-enum
FATA[05-09-2023 19:15:33] unable to retrieve item.
```
```
cat /var/log/proftpd/proftpd.log
...
2023-09-05 19:04:54,072 server03.x.y.z proftpd[127003] localhost (2a02:8070:e186:16e1:1111:222:3333:b173[2a02:8070:e186:16e1:1111:222:3333:b173]): USER ccvv_ftp1 (Login failed): No such user found
2023-09-05 19:07:03,851 server03.x.y.z proftpd[127258] localhost (2a02:8070:e186:16e1:1111:222:3333:b173[2a02:8070:e186:16e1:1111:222:3333:b173]): USER ccvv_ftp1 (Login failed): No such user found
```
```
cat /etc/crowdsec/acquis.yaml
...
---
filenames:
  - /var/log/proftpd/proftpd.log
labels:
  type: proftpd
---
...
```

**Comment by LaurenceJJones** [comment]
Same as your other issue, it only parsers failed logins, so did you attempt a failed login?

**Comment by LaurenceJJones** [comment]
Try running

```
cscli explain --log '2023-09-05 19:07:03,851 server03.x.y.z proftpd[127258] localhost (2a02:8070:e186:16e1:1111:222:3333:b173[2a02:8070:e186:16e1:1111:222:3333:b173]): USER ccvv_ftp1 (Login failed): No such user found' --type 'purepro_ftp'
```

**Comment by dwydler** [comment]
> Try running

Here the output of the command:
```
WARN[06-09-2023 12:13:32] Line 0/1 is missing evt.StrTime. It is most likely a mistake as it will prevent your logs to be processed in time-machine/forensic mode.
line: 2023-09-05 19:07:03,851 server03.x.y.z proftpd[127258] localhost (2a02:8070:e186:16e1:1111:222:3333:b173[2a02:8070:e186:16e1:1111:222:3333:b173]): USER ccvv_ftp1 (Login failed): No such user found
        ├ s00-raw
        |       ├ 🟢 crowdsecurity/non-syslog (+5 ~8)
        |       └ 🔴 crowdsecurity/syslog-logs
        ├ s01-parse
        |       ├ 🔴 crowdsecurity/apache2-logs
        |       ├ 🔴 crowdsecurity/dovecot-logs
        |       ├ 🔴 crowdsecurity/mariadb-logs
        |       ├ 🔴 crowdsecurity/postfix-logs
        |       ├ 🔴 crowdsecurity/postscreen-logs
        |       ├ 🔴 crowdsecurity/sshd-logs
        |       └ 🔴 proftpd-logs
        └-------- parser failure 🔴
```
The snippet of the logfile is from proFTPd 1.3.7c, Ubuntu 22.04 LTS. In my test i used the correct username but an false password.

**Comment by dwydler** [comment]
After some tests, i found the fault why only this line in the ProFTPd Log not parsed.

The Regex/Pattern is not correct anymore. This is the orginal line:
```
 PROFTPD_AUTH_FAIL: '%{TIMESTAMP_ISO8601:timestamp} %{IPORHOST:hostname} proftpd\[%{DATA}\] %{IPORHOST:hostname} \(%{IPORHOST}\[%{IP:source_ip}\]\): USER %{USERNAME:username} \(Login failed\): Incorrect password'
```
With the proFTPd Version under Ubuntu 22.04 LTS there is a little change in the error message. So it is necessary to replace the text on the end:
```
PROFTPD_AUTH_FAIL: '%{TIMESTAMP_ISO8601:timestamp} %{IPORHOST:hostname} proftpd\[%{DATA}\] %{IPORHOST:hostname} \(%{IPORHOST}\[%{IP:source_ip}\]\): USER %{USERNAME:username} \(Login failed\): No such user found'
```
After that the line is parsed correctly.

What is now the best way to implement this without to lose the compatibility to older versions of ProFTPd?

**Comment by LaurenceJJones** [comment]
I will compare the two and offer an update soon

**Comment by Lawkss** [comment]
But both error messages exist? If I enter a wrong user I get the wrong user message, If I enter correct user but wrong PW I get the original line. 

Either way I am not getting any bans/decisions/alerts. 

I have a default install where without setting acquis.yaml entry

should it not work automatically when proftpd is logging to /var/log/secure?

**Comment by LaurenceJJones** [comment]
> should it not work automatically when proftpd is logging to /var/log/secure?

I dont know I don't use it... can you post some full line examples from /var/log/secure

**Comment by Lawkss** [comment]
```
Sep 11 20:52:58 home proftpd[117894]: pam_unix(proftpd:auth): authentication failure; logname= uid=0 euid=0 tty=/dev/ftpd117894 ruser=vom-bruch rhost=2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX  user=luca
Sep 11 20:53:00 home proftpd[117894]: 192.168.0.5 (2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX[2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX]) - USER luca (Login failed): Incorrect password
```

`Sep 11 20:52:01 home proftpd[117795]: 192.168.0.5 (2a00:98c7:1000:1300:aaa1:59ff:fXXX:XXX[2a00:98c7:1000:1300:aaa1:59ff:XXX:XXX]) - USER test: no such user found from 2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX [2a00:98c7:1000:1300:aaa1:59ff:fXXX:XXXX] to 2a00:98c7:1000:1300:6e4b:90ff:fe57:XXXX:21`

**Comment by dwydler** [comment]
> Sep 11 20:52:58 home proftpd[117894]: pam_unix(proftpd:auth): authentication failure; logname= uid=0 euid=0 tty=/dev/ftpd117894 ruser=luca rhost=2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX  user=luca
> Sep 11 20:53:00 home proftpd[117894]: 192.168.0.5 (2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX[2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX]) - USER luca (Login failed): Incorrect password

What operating system do you use and which version? Which version proFTPD is installed?
You can simple testing der parser with follow commands and post the output here:
```
cscli explain --log 'Sep 11 20:52:58 home proftpd[117894]: pam_unix(proftpd:auth): authentication failure; logname= uid=0 euid=0 tty=/dev/ftpd117894 ruser=luca rhost=2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX  user=luca
' --type 'proftpd'
cscli explain --log 'Sep 11 20:53:00 home proftpd[117894]: 192.168.0.5 (2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX[2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX]) - USER luca (Login failed): Incorrect password
' --type 'proftpd'
```
If I saw it correctly, the structure of the log file has not been taken into account so far.

> Do I have to manually set it to /var/log/secure?

You have to adjust the configuration section in the [Acquisition template.](https://hub.crowdsec.net/author/crowdsecurity/collections/proftpd#acquisition-template)

> according to cscli metrics it is being read. But I dont know if proftpd is active for it.

Did you installed the proftpd Collection ([Manual](https://hub.crowdsec.net/author/crowdsecurity/collections/proftpd))?

**Comment by Lawkss** [comment]
Almalinux 9.2
ProFTPd version 1.38

` cscli explain --log 'Sep 13 20:28:23 home proftpd[353984]: 0.0                                                                                                                                                                                                                                                                                                                                                           .0.0 (41.214.134.200[41.214.134.200]) - USER root (Login failed): Incorrect pass                                                                                                                                                                                                                                                                                                                                                           word' --type 'proftpd'
line: Sep 13 20:28:23 home proftpd[353984]: 0.0.0.0 (41.214.134.200[41.214.134.2                                                                                                                                                                                                                                                                                                                                                           00]) - USER root (Login failed): Incorrect password
        ├ s00-raw
        |       ├ 🟢 crowdsecurity/non-syslog (+5 ~8)
        |       └ 🔴 crowdsecurity/syslog-logs
        ├ s01-parse
        |       ├ 🔴 crowdsecurity/apache2-logs
        |       ├ 🔴 crowdsecurity/dovecot-logs
        |       ├ 🔴 crowdsecurity/nextcloud-logs
        |       ├ 🔴 crowdsecurity/postfix-logs
        |       ├ 🔴 crowdsecurity/postscreen-logs
        |       └ 🟢 proftpd-logs (+7 ~2)
        ├ s02-enrich
        |       ├ 🟢 crowdsecurity/dateparse-enrich (+2 ~2)
        |       ├ 🟢 crowdsecurity/geoip-enrich (+13)
        |       ├ 🔴 crowdsecurity/http-logs
        |       ├ 🔴 crowdsecurity/nextcloud-whitelist
        |       └ 🟢 crowdsecurity/whitelists (unchanged)
        ├-------- parser success 🟢
        ├ Scenarios
                ├ 🟢 crowdsecurity/proftpd-bf
                └ 🟢 crowdsecurity/proftpd-bf_user-enum

`

I did not add anything to acquisition, it already reads /var/log/secure

**Comment by dwydler** [comment]
You tested only the last line of excerpt from the log file. What is the output of the first line?
```
cscli explain --log 'Sep 11 20:52:58 home proftpd[117894]: pam_unix(proftpd:auth): authentication failure; logname= uid=0 euid=0 tty=/dev/ftpd117894 ruser=luca rhost=2a00:98c7:1000:1300:aaa1:59ff:XXXX:XXXX  user=luca
' --type 'proftpd'
```

> I did not add anything to acquisition, it already reads /var/log/secure

Perhaps it is the default logfile in the distribution that you used.

**Comment by Lawkss** [comment]
cscli metrics has it though: 

Acquisition Metrics:
╭───────────────────────────────────────────────────┬────────────┬──────────────┬────────────────┬────────────────────────╮
│                      Source                       │ Lines read │ Lines parsed │ Lines unparsed │ Lines poured to bucket │
├───────────────────────────────────────────────────┼────────────┼──────────────┼────────────────┼────────────────────────┤
│ file:/var/log/messages                            │ 123.66k    │ -            │ 123.66k        │ -                      │
│ file:/var/log/secure                              │ 15.41k     │ 13           │ 15.39k         │ 10                     │
│ file:/var/log/virtualmin/vom-bruch.com_access_log │ 1.27k      │ 1.27k        │ -              │ 967                    │
│ file:/var/log/virtualmin/vom-bruch.com_error_log  │ 17         │ 17           │ -              │ -                      │
╰───────────────────────────────────────────────────┴────────────┴──────────────┴────────────────┴────────────────────────╯

**Comment by Lawkss** [comment]
maybe I was in the wrong log. Also this:

` cscli explain --log 'Sep 13 21:31:28 home proftpd[359231]: 192                                                                                                                                                                                                                                                                                                                                                           .168.0.5 (35.216.181.245[35.216.181.245]) - USER anonymous: no such user found f                                                                                                                                                                                                                                                                                                                                                           rom 35.216.181.245 [35.216.181.245] to ::ffff:192.168.0.5:21' --type 'proftpd'
line: Sep 13 21:31:28 home proftpd[359231]: 192.168.0.5 (35.216.181.245[35.216.1                                                                                                                                                                                                                                                                                                                                                           81.245]) - USER anonymous: no such user found from 35.216.181.245 [35.216.181.24                                                                                                                                                                                                                                                                                                                                                           5] to ::ffff:192.168.0.5:21
        ├ s00-raw
        |       ├ 🟢 crowdsecurity/non-syslog (+5 ~8)
        |       └ 🔴 crowdsecurity/syslog-logs
        ├ s01-parse
        |       ├ 🔴 crowdsecurity/apache2-logs
        |       ├ 🔴 crowdsecurity/dovecot-logs
        |       ├ 🔴 crowdsecurity/nextcloud-logs
        |       ├ 🔴 crowdsecurity/postfix-logs
        |       ├ 🔴 crowdsecurity/postscreen-logs
        |       └ 🟢 proftpd-logs (+8 ~2)
        ├ s02-enrich
        |       ├ 🟢 crowdsecurity/dateparse-enrich (+2 ~2)
        |       ├ 🟢 crowdsecurity/geoip-enrich (+13)
        |       ├ 🔴 crowdsecurity/http-logs
        |       ├ 🔴 crowdsecurity/nextcloud-whitelist
        |       └ 🟢 crowdsecurity/whitelists (unchanged)
        ├-------- parser success 🟢
        ├ Scenarios
                ├ 🟢 crowdsecurity/proftpd-bf
                └ 🟢 crowdsecurity/proftpd-bf_user-enum`

**Comment by dwydler** [comment]
It looks like good. In your case anything work as it should.

**Comment by dwydler** [comment]
@LaurenceJJones 
Thanks for the updating the files.
Until when will the new version be distributed via the hub?

**Comment by LaurenceJJones** [comment]
> @LaurenceJJones Thanks for the updating the files. Until when will the new version be distributed via the hub?

If your on latest you can `cscli hub update` and `cscli hub upgrade`. if your parser is tainted due to local modification you can pass the `--force` flag
