### ISSUE TITLE
SSH successful collection

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/hub#824]
After https://www.crowdsec.net/blog/detecting-successful-ssh-brute-force we should package up a collection that can detect successful ssh logins and can generate an alert and decisions on the last IP

(Note I will inform this is not a silver bullet unless they also temporary ban the user as they can switch IP and just relogin)

- [x] Create successful ssh collection
- [x] Include details about notifications and that it bans the last IP
- [x] Write a blog article about using custom bouncer to temporary block users

**Comment by LaurenceJJones** [comment]
Link to #825

**Comment by Eirikr70** [comment]
Hello, with Debian Bookworm abandoning auth.log for ssh connexions, will Crowdsec provide a solution for securing ssh ?

**Comment by LaurenceJJones** [comment]
> Hello, with Debian Bookworm abandoning auth.log for ssh connexions, will Crowdsec provide a solution for securing ssh ?

Yes we support journald output, [documentation](https://docs.crowdsec.net/docs/next/data_sources/journald#configuration-example) where you can see the current ssh example for debian 12

**Comment by Eirikr70** [comment]
How can Crowdsec, installed in a Docker container, read the syslog of the host ?

**Comment by LaurenceJJones** [comment]
> How can Crowdsec, installed in a Docker container, read the syslog of the host ?

Mount the journal files from the host into the container, and then setup acquisition to find the files via journald. You need to use the `debian` flavour tag as that one that has journalctl binary

Here an example of acquisition https://github.com/crowdsecurity/home-assistant-addons/blob/234549b74260ae698c5f6462a19ad5f27f7b5b5f/crowdsec/config.yaml#L23-L28

**Comment by LaurenceJJones** [comment]
> I get this fatal error
> 
> ```
> crowdsec  | time="19-01-2024 19:00:02" level=info msg="initiating plugin broker"
> crowdsec  | time="19-01-2024 19:00:02" level=fatal msg="api server init: unable to run plugin broker: while loading plugin: while getting process attributes: group: unknown group nobody"
> crowdsec  | time="19-01-2024 19:00:02" level=fatal msg="api server init: unable to run plugin broker: while loading plugin: while getting process attributes: group: unknown group nobody"
> ```
> 
> I have tried to change the user in the `config.yaml`, with no success

https://github.com/crowdsecurity/crowdsec/issues/2711

So for debian the valid confguration is

```
user: nobody
group: nogroup
```
