### ISSUE TITLE
Documentation or fix for cdn-whitelist needed

### ISSUE THREAD

**Issue by watou** [crowdsecurity/hub#881]
The file `postoverflows/s01-whitelist/crowdsecurity/cdn-whitelist.yaml` shows that the CloudFlare IPs are being retrieved at some point and being written to a text file, but there is no documentation that I can find that says this is a frequently recurring process, which it absolutely must be.

If CloudFlare were to ever change its lists of IP ranges for IPv4 or IPv6, but CrowdSec did not quickly adjust to this change, instead relying on what it retrieved once upon a time, the clear risk of banning un-whitelisted addresses would immediately exist.  This would become an extremely difficult to diagnose problem experienced by web clients from that point forward.

So either 1) the code that handles this YAML file repeatedly retrieves the currently true set of CloudFlare IP address ranges and CrowdSec uses them in real time and this should be clearly documented, or 2) this YAML file represents a distinct risk of future problems that will be extremely difficult to isolate and correct.

**Comment by LaurenceJJones** [comment]
Hey 👋 

Currently, the only way for the files to be updated would be to run the `cscli parsers install` command with the `--force` flag.

There is going to be a fix in the near future that will handle file invalidation and updates.

**Comment by watou** [comment]
Thanks; brilliant news.  In the meantime I will have a daily cron job that forces reinstall and reloads crowdsec.
