### ISSUE TITLE
How to use the collections of schiz0phr3ne (radarr,sonarr,prowlarr)?

### ISSUE THREAD

**Issue by saschabrockel** [crowdsecurity/hub#911]
https://github.com/crowdsecurity/hub/blob/master/collections/schiz0phr3ne/radarr.yaml

I'm talking about the link. It's nice that this exists but there is no manual. I don't know how to map it. For all other collections it is documented:

e.g.:
```
filenames:
  - /var/log/paperless.log
labels:
    type: Paperless-ngx
```

@schiz0phr3ne can you tell it? :)

**Comment by LaurenceJJones** [comment]
Might be a good idea to inform how you are running these? cause the instructions may change if you running them inside a container environment.

**Comment by saschabrockel** [comment]
True. I run crowdsec and all of the listed apps in Docker.

**Comment by andreasbrett** [comment]
It's documented in the parser.

https://github.com/crowdsecurity/hub/blob/master/parsers/s01-parse/schiz0phr3ne/radarr-logs.md
