### ISSUE TITLE
Personal Git repo support?

### ISSUE THREAD

**Issue by dlprows** [crowdsecurity/hub#989]
Apologies if this is not the right form to ask. 
Does crowdsec have any support for local repositories for collections, or is it only through this hub?

I understand the philosophy of crowd sourcing security, and therefore wanting to push people toward making their custom parsers public so that anyone can use them. But it also introduces a lot of friction when trying to get the right person informed of a bug in the parser they provided.

And if i make my own parser, it would be nice to be able to store it in git instead of having it only exist on my crowdsec server.

Is this functionality that exists that i missed?

**Comment by LaurenceJJones** [comment]
> Does crowdsec have any support for local repositories for collections, or is it only through this hub?

Current we only have the Hub, we been playing around the idea of having multiple sources but its add a lot of complexity to the code base. When a user if they wanted can simply just have a repository that they can pull from and merge the contents. Or use something like rsync.

> But it also introduces a lot of friction when trying to get the right person informed of a bug in the parser they provided.

Most of the time we (crowdsec) try to maintain any hub items moving forward, the main issue that we see is when users report an issue they and us are not highly knowledgeable of the product, so making changes to the parsers / scenarios may infact be to the detriment of the community.

So our response normally to a report on a parser is provide us an example log line so we can test and add it to the test files (they can redact any PII data from the log line)

**Comment by dlprows** [comment]
That makes a lot of sense.
I apologize that my response is likely going to come across as long winded, but its because I find that github issues can often leave a useful paper trail for people in the future. I'm pretty sure there's a discord, but personally, I am a lot more likely to search issues on github instead of joining yet another discord group to ask one question, and then ride off into the sunset.


When I initially asked about this, I think that initially I was thinking that it would be more important to be able to install personal/private collections because I was thinking of things more from the fail2ban side of things where you might have to write a scenario where you're tying into some kind of super custom api, or having some kind of parser that is extremely specific to your individual circumstances.

But after having read your explanation, and some time to think about it more, I can understand how the main maintenance would just become the parsers, because the scenarios just have to be generic ways of detecting potential problems. And then the agent only has to interact with LAPI. And so with example logs, It makes a lot of sense how it could reasonably be maintained without the need of contacting the original author.

So that leaves the main reason i can think of for private repositories being that there doesn't seem to be any configuration options for collections in the hub.
So for example, i found myself beating my head against a wall because of a timezone issue, because one of my apps was writing logs out in local time zone. All my docker containers all had the right time and timezone if i ran `date` but one container was writing logs using local time, and the agent seems only capable of assuming that they're in UTC. And i found myself trying to figure out why the parsers didn't have some kind of configuration so that you didn't have fix the log or parser, but could just change a configuration.

My eventual solution was to make my own copy of the collection, make the changes I needed, and then submit an issue. 
So realistically having the ability to have custom repositories could make it easier to fragment the system, and make things more difficult to work with instead of less. 
This would happen because if I have my system all set up and working, and someone submits an issue to my individual github, I'd be a lot less inclined to "fix" the issue, because it works on my machine. Whereas a central maintenance group doesn't necessarily have that same conflict of interest
