### ISSUE TITLE
New version of OWASP CRS breaks the Modsecurity parser

### ISSUE THREAD

**Issue by ne20002** [crowdsecurity/hub#996]
**Describe the bug**
With version 4 of [OWASP CRS](https://github.com/coreruleset) the logging information in Nginx/Apache error.log has been changed. 

**To Reproduce**
Update OWASP CRS to version 4.

**Expected behavior**
Crowdsec should still detect relevant information.

**Additional context**
An [issue](https://github.com/coreruleset/modsecurity-crs-docker/issues/215) has already been filed at CRS project to discuss the matter.

**Comment by dune73** [comment]
OWASP CRS project leader here.

We are tracking this issue at https://github.com/coreruleset/coreruleset/issues/3607 and in the issue linked above.

We are still trying to find out what the matter is with original reporter, but we doubt it's a CRS problem even if the tagging in our blocking message did change slightly.

**Comment by ne20002** [comment]
The problem affects only Modsecurity3 / Nginx. If Nginx error log level is set to 'info', the dectection rules are logged to error log and the Crowdsec parser will work properly with the current configuration.
